### ISSUE TITLE
Suggestions how to embed Time4A as calculator

### ISSUE THREAD

**Issue by MenoData** [forrestguice/SuntimesWidget#103]
After having seen your new time4a-branch, I just open this issue in order to be able to comment the first draft:

-  First I kindly suggest you to use [another factory method](http://time4j.net/javadoc-en/net/time4j/calendar/astro/SolarTime.html#ofLocation-double-double-int-net.time4j.calendar.astro.SolarTime.Calculator-) to create a new instance of `SolarTime`.

- Main reason is to get the chance to embed different variants of Time4J-calculators. There are four built-in calculators, see the enum [StdSolarCalculator](http://time4j.net/javadoc-en/net/time4j/calendar/astro/StdSolarCalculator.html). So the design idea would rather be to embed 3 or 4 subclasses of `.../time4a/SunriseSunsetSuntimesCalculator`, each one with a different name like "time4a-NOAA" etc. Well, the SIMPLE-calculator might be left out because it is practically the same calculator as the library of Mike Reedell.

- Another reason is to get the chance to evaluate the altitude of given location because at least the calculators `StdSolarCalculator.TIME4J` and `StdSolarCalculator.CC` indeed use this altitude for corrections of sunrise/sunset-calculations.

- I am not sure if the state of suggested new `SunriseSunsetSuntimesCalculator`-facade requires a member of type `WidgetSettings.Location` because the `SolarTime`-instance also stores this information. Looks like redundant.

- I am also not sure if it is necessary to store an extra member of type `java.util.TimeZone` because your comment in lines 72/73 says that the timezone stored inside the passed `Calendar`-date-object is the same as passed to the `init(...)`-method.

- For the necessary conversion from `java.util.Calendar` (date-input to various calculation methods) to `PlainDate` (which implements the interface `CalendarDate`), I suggest renaming the calculator-member to "solarTime" and use following code (which can be factored out to a private static conversion method):

```
Moment moment = TemporalType.JAVA_UTIL_DATE.translate(dateInput.getTime());
ZonalOffset offset = ZonalOffset.atLongitude(new BigDecimal(this.solarTime.getLongitude()));
PlainDate localDate = moment.toZonalTimestamp(offset).toDate();
```
- Then, a typical implementation of the calculation methods looks like this:
```
@Override
public Calendar getNauticalSunriseCalendarForDate(Calendar dateInput) {
  PlainDate localDate = convert(dateInput); // as shown above
  Moment sunrise = localDate.get(this.solarTime.sunrise(Twilight.NAUTICAL)); // attention: nullable!
  if (sunrise == null) {
    return null; // event does not exist - a valid and possible result at higher latitudes
  } else {
    GregorianCalendar gcal = new GregorianCalendar();
    gcal.setTimeZone(dateInput.getTimeZone());
    gcal.setTime(TemporalType.JAVA_UTIL_DATE.from(sunrise));
    return gcal;
  }
}

```

- Methods like `getSolarNoonCalendarForDate(...)` would delegate to `this.solarTime.transitAtNoon()` else the implementation is very similar to the example above.

- About the method `public boolean isDay(Calendar dateTime)`, it seems to be a kind of instant i.e. not intended as a local calendar date). If so then I suggest to use this implementation using the platform timezone rules:

```
PlainDate localDate = convert(dateTime);
TZID tzid = Timezone.of("java.util.TimeZone~" + dateTime.getTimeZone().getID()).getID();
Moment moment = TemporalType.JAVA_UTIL_DATE.translate(dateTime.getTime());
return localDate.get(this.solarTime.sunshine(tzid)).isPresent(moment);
```
By the way, I have noticed a bug in [your code](https://github.com/forrestguice/SuntimesWidget/blob/5f9f7d17ea5c0f3af9ae3f7e49d45d86eb4236ee/app/src/main/java/com/forrestguice/suntimeswidget/calculator/sunrisesunset_java/SunriseSunsetSuntimesCalculator.java#L174) using the lib of M. Reedell for determining if it is day or not. If a sunrise (or sunset) event does not exist then it does not necessarily mean that the sun can be determined as above or below the horizon all the day. This requires an extra calculation as internally done in Time4J. Caarmen-library has also done such a calculation and offers a [public method](https://github.com/caarmen/SunriseSunset/blob/0caf4967eae9da45b1d81836c862c8f78a2ae8f0/library/src/main/java/ca/rmen/sunrisesunset/SunriseSunset.java#L442) for this purpose (but IMHO not completely reliable near equinox dates).  Think of polar night or midnight sun (there is no sunrise or sunset on such days in circumpolar regions).

- It is also possible to calculate the golden hour. It is not mentioned in enum `Twilight` because the golden hour happens when the sun is still above the horizon. But you can call the method `solarTime.getCalculator().sunrise(...)` (or sunset(...)) and pass as zenith angle the angle `90 + geodeticAngle - goldenHourAngle` where the geodetic angle can be determined by calling another method on `solarTime.getCalculator()` (altitude correction) and the golden hour angle is typically around 10-12 degrees (but no clear definition exists).

**Comment by MenoData** [comment]
I have now also seen an implementation of the equation of time in the class [WidgetTimeZones](https://github.com/forrestguice/SuntimesWidget/blob/433e5ef59d200da87a91aea7c0f8702c64a96cf2/app/src/main/java/com/forrestguice/suntimeswidget/settings/WidgetTimezones.java#L259). Well, maybe you are interested to see that there are different implementations. Time4A also offers such code and a public method in the enum `StdSolarCalculator`.

**Comment by forrestguice** [comment]
Nice, thanks for taking the time to look around w/ a critical eye. I agree w/ everything written. I'll get going on this over the weekend.

- Embedding time4a multiple times, one for each variant, is a great idea. I hadn't looked too closely at those other algorithms, but offering an option for each is going to be a really nice enhancement. Same with actually using the altitude data.

- yep, the WidgetSettings.Location isn't needed here. redundant.

- same for TimeZone member. redundant. some history here.. initially the timezone was only provided in init() and the Calendar wasn't explicitly zoned. It picked this property up after I tried wrapping the ca.rmen lib and discovered it needed this (and didn't accept timezone input another way). I thought I'd point it out because it seems "warty" to me.

- thanks for the code snippet for conversion from Calendar. 3 lines, very straightforward, but I'm glad I asked. Same for the typical implementation .. extremely helpful, I'll have no trouble writing the other methods.

- good observations for isDay. Definitely a bug there (that manifests itself in a couple ways). I was pretty happy to delegate that code to ca.rmen but kept the existing buggy code as it was. Fortunately isDay hasn't been used for much; determining the app theme when set to "nightmode", and drawing the right foreground color in the "lightmap". 

- At the moment golden hour is not used/displayed anywhere, but its good to know I can supply an arbitrary zenith. The blue hour is also unused. In an attempt at prescience, I added those to the interface after noticing them as requests in the sunrisesunsetlib issue tracker. I was hoping to avoid additional interface changes down the line. So far so good.

- Good to know about the different implementations of equation of time. I will have to take a closer look and maybe refactor. I was a bit worried those custom TimeZone classes would pose an obstacle, but it seems not. When I wrote them it seemed like a good solution to implementing "solar time" without having to change anything else, just another offset/correction. I don't think I've seen anyone else (ab)using TimeZone this way, but seems to work o.k.
