### ISSUE TITLE
altitude

### ISSUE THREAD

**Issue by forrestguice** [forrestguice/SuntimesWidget#110]
Some algorithms allow refinements based on altitude. The altitude is automatically used by these data sources when location data is provided by the GPS, however there is currently no way to manually input altitude, or any indication in the UI that refinements are being applied.

1) extend the LocationDialog to allow manual input of altitude.
2) add an altitude label somewhere in the app layout.
3) add altitude to widget title substitutions.

**Comment by MenoData** [comment]
For your information: The current default datasource "time4a-noaa" does not take into account the altitude of observer, but the sources "time4a-cc" and "time4a-time4j" do. 

The question arises what the app should do if the user specifies an altitude. Maybe it is possible to dynamically change the default from "time4a-noaa" to let's say "time4a-time4j" if and only if the user specifies an altitude. This way, the default noaa-source would still be chosen in normal cases as a good compromise between speed and accuracy. What do you think?

**Comment by forrestguice** [comment]
That does add a wrinkle to things. For the time4a-sources I think dynamically swapping to the 4j implementation as features are needed (like altitude) is definitely doable. I will need to give the specifics some thought.

I think this highlights a larger issue though, which is that not all implementations have the same capabilities, and don't have a way to advertise that to the UI. For example, what should the app do when the old sunrisesunsetlib source is selected - my thinking is it should disable the altitude fields (or visually indicate lack of support some other way). Perhaps if the fields are clicked, the app could prompt to change to a supported source, and then display the configuration activity w/ a filtered list. In a similar vein, the data source ui could also indicate capabilities (maybe a sequence of icons integrated into the selector).

**Comment by forrestguice** [comment]
I've been finishing up the solstice/equinox stuff and have noticed a similar wrinkle there. After adding solstice/equinox functions to the Suntimes interface, it started to become apparent that maybe grouping that w/ the rise/set stuff wasn't internally consistent, at least not for the time4a-sources. They all share the same base class, which means those solstice/equinox functions work for all of them, even though I think in actuality the calculations use algorithms by Meeus (which would technically put that functionality into the time4a-4j source).

Maybe this misleads users into thinking the solstice/equinox times are calculated in a manner thats consistent w/ the rise/set times. I dunno. I don't think its an actual problem (not one I'm going to fix at least), and maybe its just an implicit version of whats described above - dynamically changing to the 4j sources as features are needed.

**Comment by MenoData** [comment]
Indeed, not all implementations have the same capabilities. What you suggest on the level of UI (disabled fields, informational prompts or help windows etc.) is interesting. About the different algorithms in Time4J/A: 

I was mainly inspired by this [issue](https://github.com/mikereedell/sunrisesunsetlib-java/issues/32) where some people like to get the option to compare different methods to determine sunrise/sunset. But I have also limited my differentiation only to this topic and not tried to realize a general-purpose calculator for more astronomical subjects. Therefore there is only one implementation for solstices/equinox.

On the other side, even a "single" source like the book "Astronomical Algorithms" from Jean Meeus contains several ways to calculate results to a special topic so I had to choose. We can even argue that NOAA has finally based its algorithms on that book of Meeus, too so we can not generally say, only the "time4a-time4j"-version follows Meeus and the other not (with the exception of the version "time4a-simple").

Actually, I am working on moon positions and moonrise/moonset.  There is already [a commit for the moon position](https://github.com/MenoData/Time4J/commit/e75d117cb96b8249b50f2958f978998805a318ac) based again on formula and data of Meeus. It runs fine on my laptop but I am not sure if it also runs on mobile phones in an acceptable speed because a lot of calculations is involved. As alternative, I can also imagine to implement a short version which would be quicker but unavoidably less accurate (several minutes deviation which does not satisfy everyone). So I am uncertain if splitting the algorithm here is worth the effort in order to have more speed.

I also suspect that most users don't want to think too much about choosing multiple calculators. It should _just_ work. The configuration effort and help should not be so complex for users.

**Comment by MenoData** [comment]
Maybe it is also an interesting idea to find a simpler configuration scheme for choosing a suitable calculator like "simple versus accurate". This would work in case of moonrise/moonset.

**Comment by forrestguice** [comment]
I like the idea of a "simple vs accurate" feature. Instead of choosing a specific calculator user's might choose between 'simple', 'accurate', or 'user defined'. The first two are a form of automatic mode where the app chooses as appropriate, and the last a manual mode (the way it works now).

You are right, most users don't want to think about this stuff. It should just work.
