### ISSUE TITLE
Widget shows different times from app with same config

### ISSUE THREAD

**Issue by rrthomas** [forrestguice/SuntimesWidget#117]
Right now, for Europe/London, the widget is showing 07:36 sunrise/15:59 sunset. In the app, for today, it shows 07:38/15:55. It looks like it's showing yesterday's times in the widget. (All times are configured to Actual.) I'm using version 0.4.1 from F-Droid.

**Comment by rrthomas** [comment]
I just found the 0.5.0 update, and the problem is still there.

**Comment by rrthomas** [comment]
Apologies, the widget is using London (geographical position); the app is using my actual position (right now about 60 miles away in Cambridge). It's confusing because the app still says "London". Still, this is not a bug as reported, so closing.

**Comment by forrestguice** [comment]
Hi. Thanks for reporting your experience. I'm glad you were able to figure out what was going on (and determine there isn't a bug). I'd like to understand a little better (and maybe find ways to improve the ui).

When the app says "London", is it similar to the following screenshot where the label circled in red reads "Phoenix"? This is actually the timezone label, but it wouldn't be the first time its been confused for the location (in blue). 

![screenshot_2017-11-26-20-14-38](https://user-images.githubusercontent.com/10246147/33249234-9acc68f6-d2e6-11e7-9cdc-264f02772f98.png)

Also, I want to confirm that the app using "Current (last known)" location mode (and not "User Defined" and perhaps acting in some unexpected way).

**Comment by rrthomas** [comment]
Thanks very much for looking into this. My confusion is exactly as you describe, the display looks like the screenshot, and I was indeed using Current location mode.

My biggest confusion is over why I can't select that mode for the widget (it's greyed out).

**Comment by forrestguice** [comment]
thanks, that clears things up for me.

The "current location" mode isn't implemented for widgets (yet), but it appears in the configuration anyway because of shared code. Its grayed intentionally to prevent selection since the widgets currently have no notion of "current location" or location updates. 

For my own personal use case I pretty much always use "user defined" mode. I think to properly implement this would require the widgets to be backed by a Service that listens for location broadcasts. The flippable widget is already backed by such a service (and could probably be finished w/ a few lines), but changing the other widget is will probably be less straightforward. I've been putting it off.

So its a combination of laziness and lack of demand/motivation on my part. ;)

**Comment by XanderLeaDaren** [comment]
I discovered I have the same issue when using the “display local solar time” widget and the “set alarm clocks according to local solar time”, because you have to specify a place and you cannot chose the last known GPS location/position as you do in the general application. Is there any new motivation on this part nowadays? ;)
