### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by HerHde** [forrestguice/SuntimesWidget#15]
Ahoi,
could you give me some help with the german translation, please?

1.- daylenght - could you please explain those to me? How are they calculated, which differences are this?
```xml
    <!-- Field: length of day
         The hours in the day field(s) that appears below the table (main activity).
         (layout/info_time_daylength.xml)
    -->
    <string name="length_day">in the day</string>
    <string name="length_light">of usable light</string>
```
2.- daydelta - where do these strings appear?
```xml
  <!-- Field: today/tomorrow time delta
       (layout/info_time_daydelta.xml)
  -->
  <string name="delta_day_tomorrow">Tomorrow will be</string>
  <string name="delta_day_yesterday">Yesterday was</string>
```
3.- Note - I've translated it as *Kurzinfo*, which means something like *short information*, don't know any better approach yet, because *note* is *Notiz* in german, which primarily means *memo*, a little bit misleading IMHO.

4.- Widget Setting: date mode - I can't find these within the app?!?
```xml
  <string name="configLabel_date">Date Settings</string>
  <string name="configLabel_date_mode">Mode:</string>
  <string name="configLabel_date_custom">Date:</string>
```
5.- gps_lastfix, gps_keeptrying and the toast - Could you please provide a screenshot of their appearance?

Except of these, the translation is almost ready for a first release ;-)

Greetings
~HerHde

**Comment by forrestguice** [comment]
1. `length_day` is timespan from sunrise to sunset, and `length_light` from start of morning to end of evening civil twilight. I will add it to the help text; a new string value (call it `help_general_daylength`) where it can be explained.

2. it should be possible to highlight a widget and expand it horizontally to show alternate layouts (although I just tried and had some issues getting it to update, so might be a few bugs here). The larger layout should say something like "tomorrow will be 2m shorter" or "yesterday was 2min longer" in addition to showing the times .. I just checked, those "shorter" and "longer" values are missing from `strings.xml` (hardcoded). I'll add them as `delta_day_shorter` and `delta_day_longer`.

3. I don't know of anything better either. I chose "note" when writing the classes because I didn't know what else to call it and wanted to get on with implementing what it does, and then later when adding the "tap options" was pretty much forced to give it a visible name

4. the date stuff currently appears in the app but not the widget. In the app its the "Use date" actionbar item (or tapping the dateField) which launches a dialog (containing those widget settings). Its a recent addition - it can be added to the widgetConfig activity if thats useful (I wasn't sure), so the widget could then show times for an unchanging (set) date vs just "today".

5. the `gps_lastfix` stuff is used when location mode is set to "current (last known) - that should add "refresh" as the first actionBar item, and when clicked tries to refresh location. While the gps is busy the actionbar title is changed to `gps_lastfix_title_searching` (Getting Location), and when a location is found its called `gps_lastfix_title_found` (Last Position), and then thats displayed as the title.

If the gps fails to get a location in time the `gps_lastfix_toast_notfound` toast is displayed. The `gps_lastfix_toast_cancelled` toast gets displayed if its canceled before getting a location - that will happen if you browse away from the activity (or change device orientation). 

The `gps_lastfix_title_set` is unusual - its used similar to `gps_lastfix_title_found` as a place name, but in the case the location is set by intent - this should be possible from other apps that supports the geo uri (similar to the way the "Show Map" actionBar item works).

The `keeptrying` stuff is a late addition and (tbh) untested, wouldn't surprise me if its broken. The dialog should be displayed after failing to get a location in a timely manner and is essentially asking "try again?"

**Comment by forrestguice** [comment]
Thank you. :) I've tested the german localization in the emulator and things look pretty good. Its now published as v0.1.1 (the fdroid listing still needs to be updated so that will be a couple days). 

Give it a test and close the issue if things look good (I would close it but my understanding is doing that would prevent you from reopening it later). If you've got corrections you can reopen it and submit another merge request and we'll get those fixes into the next release.

**Comment by HerHde** [comment]
Some hours ago the build and release on F-Droid was complete and I've tested it. Thank you again! With #18 I've made some minor translation improvements.
Also I've discovered that the "Export Places" and "Clear Places"-Settings are not translated, so I've added these to the strings.xml and preference_places.xml.

Unfortunately I have no idea how to build the app, so I'm depending on the F-Droid releases.

Greetings
~HerHde

**Comment by forrestguice** [comment]
merged.  The new "Export Places" and "Clear Places" strings were added correctly - that is exactly how to pull stuff into strings.

The app can be built w/ a single command "gradle build", but that requires having the android sdk installed and configured on your system (which isn't exactly easy so I'm not really expecting anyone to compile). Also, after its built I think it needs to be "signed" before it can be successfully side loaded. 

If you are on a linux distro I think the easiest route to building is in the fdroidserver installation guide, but more realistically... I'll need to look into building and distributing apks to testers myself. I'm not sure what the best way to do that is. The commerical app stores offer a web based service for this stuff. Maybe you know of an alternative for the foss crowd?

**Comment by HerHde** [comment]
The german translation seems fairly complete, I'll close this issue.

Maybe you can attach the APKs you've build when creating a new release on GitHub?
