### ISSUE TITLE
Consider "vernal equinox" and "autumnal equinox"

### ISSUE THREAD

**Issue by arschficken** [forrestguice/SuntimesWidget#159]
"Fall" isn't used to designate autumn outside of North America, and in any case [the source of all knowledge and wisdom in the world](https://en.wikipedia.org/wiki/Equinox#Names) doesn't mention "spring equinox" or "fall equinox" as names for these points in time. Please consider using the traditional names, "vernal equinox" and "autumnal equinox", at least for locales other than USA/Canada.

Also, kudos for localising based on hemisphere!

**Comment by forrestguice** [comment]
I actually started w/ the vernal/autumnal designations (and use those throughout the code), but when labeling things I intentionally avoided the Latin - my thinking was the layperson (at least in the US) wasn't going to recognize those labels (but would easily understand an association w/ the seasons). By labeling according to season (and localizing to the hemisphere), I also felt I was avoiding the ambiguity mentioned in the wiki article ...but it never occurred to me that "Fall" is a North American localization. woops.

This is something we can change easy enough w/ localization. I'm open to fixing it that way.

Speaking of the source of all knowledge and wisdom... I think it contains some factual errors (and maybe written by someone who suffered from the same confusion they were describing ;) It reads..

> The equivalent common language English terms spring equinox and autumn (or fall) equinox are even more ambiguous.[5][6][7] It has become increasingly common for people to mistakenly refer to the September equinox in the southern hemisphere as the Vernal equinox.[8][9]

lol, I brought my palm to my forehead after reading that, because it contradicts what I thought I understood. I checked the reference [9], at https://books.google.com/books?id=hs-PBSZTCBMC&pg=PT31#v=onepage&q&f=false, which (of course) explains the opposite. oy.

**Comment by forrestguice** [comment]
I propose... 1) making "Fall" specific to US / Canada (en-US, en-CA), 2) changing the default (en) to "Autumn" (but keep the phrase "Spring"), 3) and then change specific en locales to "Vernal" and "Autumnal" as appropriate.

**Comment by arschficken** [comment]
Ha, I missed that part of the page entirely, due to grepping for " fall " and being defeated by the parentheses.

Weird contradiction in the page, but it does validate the use of autumn/fall and spring. So your proposed solution is great. Just steps 1 and 2 should cover it perfectly. Thanks for considering this.
