### ISSUE TITLE
UX: Date navigation

### ISSUE THREAD

**Issue by jkufner** [forrestguice/SuntimesWidget#173]
Hello,
I find date navigation in Suntimes app quite impractical. Switching between today and tomorrow is nice, but it is not very useful when I want to see sunset time for day after tomorrow.

Another sunset/sunrise app, Sundroid, have a much better user interface to choose date:

![screenshot_2018-03-06-10-14-58](https://user-images.githubusercontent.com/16572/37023980-eb68c892-2127-11e8-81da-d41a3e1f0cdf.png)

See that little bar at bottom with arrows to show next/previous day? It is practical and intuitive. When the date in middle is clicked, a set date dialog is shown — note the "Today" button:

![screenshot_2018-03-06-10-21-55](https://user-images.githubusercontent.com/16572/37024112-44e65d26-2128-11e8-9150-1ad7a1ab2f1f.png)

However, placing the date selector at bottom of the screen is not the best. I would rather see the date navigation somewhere near the top of the screen.

All features are already present in Suntimes, so it is only about making user interface a bit better.

**Comment by forrestguice** [comment]
Thanks for the constructive criticism. I agree there is room for improvement here.
After some consideration, here is my thinking on this...

I had originally intended that the app flip forward or backward any number of days. I am going fix the UI so that it allows this - I think a RecyclerView is called for here (but unfortunately the app doesn't currently implement it that way; some refactoring required).

Its interesting to see how Sundroid approached date selection - e.g. it seems that "today" button at the bottom of the dialog reduces the number of clicks, and by contrast it takes quit a few clicks to do the same thing in Suntimes. I will look into streamlining the way this dialog works - automatically selecting "user defined" when opening the dialog through "set date" would be an improvement, as would a similar "today" button for quickly setting it back.

I agree the bar navigation w/ left and right nav buttons is very intuitive, but unfortunately vertical screen space is at a premium. I'm hesitant to add any UI elements that consume vertical space on their own (like a dedicated bar). So the date selection is probably going to remain in the main "table" area. It may be possible to move those next/prev buttons to the top (they are currently near the bottom because that is where there is room on smaller screens)

I don't want to mimic other apps too closely (I actually haven't tried Sundroid, or any other sunrise/sunset app believe it or not), but clearly there is better UX out there. This is definitely something to be improved, thanks for reporting. :)

**Comment by forrestguice** [comment]
Well, I've finally refactored the date navigation - its now possible to flip forward/backward some arbitrary number of days. This enhancement is part of v0.12.0.

I'm pretty pleased with the result, but I also realize there is room for improvement (or maybe just a complete change). Additional feedback or constructive criticisms welcomed.
