### ISSUE TITLE
Note doesn't adapt user defined dates

### ISSUE THREAD

**Issue by HerHde** [forrestguice/SuntimesWidget#19]
Ahoi Forrest!
The note displays some wrong durations, when a user defined date is set. It seems to use the difference between the selected date and today's dusks etc.
## Examples:
* Date is set to 2016-07-25, it shows ~2d 14h until sunrise.
* Date is 2016-08-01, ~4d 1h until sunset.

I hope this helps.
Greetings
~HerHde

**Comment by forrestguice** [comment]
hrm, I am not entirely sure the times are completely incorrect, but that doesn't look "right" either.

In the first case the date is "past" but it still shows "until sunrise". I think if its read as "since sunrise" (on that date) then its accurate. I'll fix this, not sure how yet - could swap "until" for "since", or just disable the note entirely for past dates.

In the second case the date is "future" and the duration is what I'm expecting, between "now" and sunset on a specific date in the future.

Can you provide another example? The duration is always measured against "now" (which I was inferring from the time the issue was opened).

**Comment by forrestguice** [comment]
fixed in v0.2.0
