### ISSUE TITLE
Request display tomorrow's sunrise once sunset time has passed

### ISSUE THREAD

**Issue by AsmGuy** [forrestguice/SuntimesWidget#190]
Please, consider changing the widget to add the option to display tomorrow's sunrise time once today's sunset time has passed.

Something like "display today's events" vs "display last and next event".

I suggest to display today's sunset time above and tomorrow's sunrise time below in this case.

Reason for change: Not having to wait until midnight to see next sunrise time in the widget.

Thanks!

**Comment by forrestguice** [comment]
rgr that. If I understand correctly, you would like the widget to only display times in the future, and update on each event (not midnight). Also (similar to the moon widget), those times should be reordered, so the next event is on top. Instead of showing todays sunrise/sunset, the widget shows the next sunrise/sunset.

**Comment by forrestguice** [comment]
*rereading* Actually, what I just described isn't the same thing (although equally possible). 

Lets try this again. If I understand correctly, you'd like the widget to show the last event (top), and next event (bottom). So for example, if you look at the widget around midday, it shows you the rise time (from this morning) and the upcoming set time (this evening). Lets say you look at the widget again just after sunset. Now it shows the sunset (from this evening) on top, and sunrise (tomorrow morning) on bottom.

**Comment by AsmGuy** [comment]
Hello Forrest. Thanks for answering!
You got it right on your last post.
Of course, this should be optional, as I guess many people out there likes the current app just fine.

**Comment by forrestguice** [comment]
Added in v0.10.0 - probably available on F-Droid in about a week.

To enable, choose `Last/Next` from the `Order` spinner (in the widget's general settings). The option is available for both the sun and moon widgets.

Please keep an eye on it. There's potential for some new bugs here, since these widgets are now dynamically choosing their layout, the times displayed, and the time of the next update. For the default `Today` option the widget behavior is unchanged (updates at midnight), but `Last/Next` should trigger an update a few moments after each event.

Also note that if the process is killed (force closed) then the scheduled updates are lost (and the widgets will display stale info). That's not a new problem but definitely easier to notice now - opening the Widget list from the app settings will (re)schedule / fix the updates.

**Comment by AsmGuy** [comment]
Thanks Forrest!
I'll test it and let you know.
