### ISSUE TITLE
Table switches unintentionally

### ISSUE THREAD

**Issue by HerHde** [forrestguice/SuntimesWidget#20]
Ahoi Forrest,
another one here ;-)
The table in the main activity switches on some events that I would not expect.
It seems to switch between today and tomorrow e.g.:
- when I am on today and click the note with the next note setting and vice versa
- when I am on tomorrow and reactivate my screen or switch back from another app.
- when I am on tomorrow and the clock shows the next minute.

The last two appear intended, what do you say?

Greetings
~HerHde

**Comment by forrestguice** [comment]
It happens when a timefield is highlighted by the note. For example, if it is currently after sunset and the note is for sunrise (tomorrow), it will highlight that field (swapping the cards if "today" is currently shown). 

At the moment that happens whenever the note is updated, which is happening in each of the cases you describe. I think its that last one (when the clock shows the next minute) that is unexpected/annoying since it steals the view against the user's intention.

What is the right behavior here? We could disable highlighting the field entirely (no more transitions at all), or maybe detect when today/tomorrow have been explicitly swapped (and then prevent the highlighting from hijacking the view), or toggle behaviors w/ an option.

**Comment by forrestguice** [comment]
fixed in v0.2.0

**Comment by forrestguice** [comment]
...still a problem.

It works correctly when pressing the next ">" and prev "<" buttons, but swiping the view triggers the bug. Even a partial swipe (that doesn't trigger a card change) seems to reset the flag, and the next update switches the table.

tested against v0.2.1, v0.3.0 (api19)
