### ISSUE TITLE
Can't enter negative degrees when configuring places in the database

### ISSUE THREAD

**Issue by LWillms** [forrestguice/SuntimesWidget#225]
OK, I found out that I can edit the database of places, and that when I edit a place, giving it new coordinates and a new name, it seems to be added. 

But unfortunately, on entering the coordinates, I can't enter negative numbers, but those are needed for places south of the equator and west of longitude zero. 

Besides, I think that editing the database of places, there should be standard operations on single entries, namely "add" (method: new) and "delete". I had added Luanda (Angola) by editing Windhoek (Namibia), but in the first try, I had deleted the latitude, and couldn't enter a negative value... I then repeated the operation of editing Windhoek, changing the name again to Luanda, and then "Luanda" hat the proper coordinates. The actual process would be easier to understand if there were an operation "copy" or "create new from this".

**Comment by forrestguice** [comment]
Hi. Thanks for reporting the issue. I'm going to need to gather some additional information. What device model / OS version are you running?

Unfortunately I can't seem to reproduce this bug on my device, or with the others I have tested with. The inputs should accept negative numbers within range, prompt when out-of-range, and the onscreen keyboard should include the necessary keys. Is the "-" key is missing from the keyboard?

A screenshot of the location dialog while its misbehaving may also be useful.

**Comment by forrestguice** [comment]
I agree the location UI can definitely be improved.

The add functionality is as you've described, occurring automatically whenever the name is changed. I think this works fine but the behavior isn't well advertised. A "copy" or "create from" function would be useful and help clarify. 

The bigger problem (in my mind) is that there is currently no way to delete single entries. The only option currently offered is to clear the entire database. I can see how annoying this would be, especially when combined with issues that prevent correctly adding locations.

The challenge is including all of this functionality in a limited space. The current dialog isn't designed for managing the database, but for getting a location quickly, and for reselecting a previous location. It has actually been a few years since that UI was written, but I remember having a hard time figuring out where to put everything, and so opted not to include "delete" or an explicit "add".

It might very well be possible to include single entry operations in some contextual way that doesn't further complicate the existing UI. I need to explore the situation again. 

Another solution, and the one I initially rejected, is to include a full fledged "waypoint manager" in the settings; a ListView showing the entire database and offering operations for each item. Although I was originally adverse to this idea (wanting to reduce the number of activities, potential maintenance, and inevitable gold plating), the app has grown a lot since then and is undeniably heavier. Adding this activity and providing a button in the location dialog to quickly navigate to it might be the best solution.

**Comment by LWillms** [comment]
The device is a Samsung J1 mini prime
The OS is Android 6.0.1

The device does not have a built in MENU key, which my previous phone it is replacing does have (HTC ChaCha).

And yes, the minus "-" key does not appear in the soft keyboard for editing the PLACE entry. 

Question: where is this list of places stored?

**Comment by forrestguice** [comment]
Thanks, this should help me reproduce it. :) I'm optimistic its a quick fix.
I am assuming you are running v0.8.6 of the app available on F-Droid?

The list of places is stored to a local sqlite database. The schema/code for that is kept in [GetFixDatabaseAdapter.java](https://github.com/forrestguice/SuntimesWidget/blob/master/app/src/main/java/com/forrestguice/suntimeswidget/getfix/GetFixDatabaseAdapter.java) The location of the db on the device is somewhere in `/data/data/` (but I've never had reason to locate it). For privacy reasons its omitted from the [backup_descriptor](https://github.com/forrestguice/SuntimesWidget/blob/master/app/src/main/res/xml/backup_descriptor.xml) to prevent it from ending up on a server somewhere.

**Comment by forrestguice** [comment]
Ok, I'm able to reproduce this on a couple Samsung devices. After searching around, I've learned its a known issue with the Samsung keyboard. https://stackoverflow.com/questions/21677695/input-type-number-not-possible-to-insert-negative-numbers-on-mobile-phone

It seems a workaround is to replace the keyboard with something else. You might try [AnySoftKeyboard](https://f-droid.org/en/packages/com.menny.android.anysoftkeyboard/) for example.

The app itself can workaround the problem by changing the `inputType` to `text` (its currently `numberSigned|numberDecimal`, forcing the full keyboard instead. The app can also fix the problem by providing its own custom keyboard (but I wouldn't call that a "quickfix").

**Comment by LWillms** [comment]
This a photo of the dialogue changing a place. There is a ".-" key, which may be nice for a cash register application, but what is needed here is a simple minus "-". 

This is a Samsung Soft-Keyboard version 1.5.97 - the latest version. German.

**Comment by LWillms** [comment]
@forrestguice: I did not see your latest before my previous comment. 

Yes, I use Suntimes version 0.8.6, downloaded from F-Droid. 

And the upload of the screen photo did not work... I try again with copy-and-paste instead of upload

**Comment by forrestguice** [comment]
> There is a ".-" key, which may be nice for a cash register application, but what is needed here is a simple minus "-".

I know what you mean, I also encountered that other keyboard with the combined "-." key. Its another custom Samsung keyboard. I initially thought it was broken, but I'm able to get a "-" by tapping it twice.

**Comment by LWillms** [comment]
There is also another numeric keyboard on my Samsung-Device, as is being presented on editing a phone number in the phone book (contacts). This has everything needed. Unfortunately I can't upload a screenshot of it, since Github became incompatible with my browser.

**Comment by LWillms** [comment]
Thanks for the hint on double-tapping the ".-" key. When in front of the complete number, it actually does insert the minus "-".  That way it can work!
