### ISSUE TITLE
Remove Calendar Permissions

### ISSUE THREAD

**Issue by mirabilos** [forrestguice/SuntimesWidget#239]
This looks like an awfully suspicious set of new permissions:

![screenshot_2018-08-19-14-52-17](https://user-images.githubusercontent.com/861078/44309117-0a80db80-a3c2-11e8-9487-c2d48c0b5bfa.png)

I’d suggest abstaining from updating, for now…

**Comment by forrestguice** [comment]
There is no backdoor. It seems Calendar integration is more trouble than its worth. :\ The `sync` permissions are necessary to add/remove custom calendars, and the `calendar` permissions themselves necessary to add/remove events.  The new features (and permissions) are documented in the readme, the [changelog](https://github.com/forrestguice/SuntimesWidget/blob/master/CHANGELOG.md), and in the About dialog.

It is a scary looking message. A bad actor could use the Calendar permissions to steal your calendar, spam your contacts, or probably worse.  Suntimes doesn't do any of that of course. The code that uses these permissions is kept [here](https://github.com/forrestguice/SuntimesWidget/tree/master/app/src/main/java/com/forrestguice/suntimeswidget/calendar). It creates its own calendars and populates them with its own events, and doesn't go anywhere near your other calendars. The permission is requested (similar to `location`) before the feature can be used - in this case to check/uncheck the Calendar setting (which triggers the add/remove process). 

I'm now seriously considering removing the Calendar integration. I personally don't have any strong attachment to it (can live without it), and I'm not sure its worth dealing with potential mistrust over it.

**Comment by forrestguice** [comment]
btw, I think a "proper" backdoor would probably require `network` permissions ;) .. That is a permission that will never be added.

**Comment by mirabilos** [comment]
Forrest Guice dixit:

>btw, I think a "proper" backdoor would probably require `network`
>permissions ;) .. That is a permission that will never be added.

Ah okay. I don’t know Android well (I’m a Unix expert), so that
is non-obvious.

Other äpps describe the needed permissions in detail in their
package description in F-Droid… that plus your explanation in
the previous eMail would go some way towards keeping user trust,
but as you said, if it’s more hassle than worth…

Thanks for the explanation!

**Comment by forrestguice** [comment]
I agree the description is a good place for this. I will put something in there asap (when https://gitlab.com/fdroid/fdroiddata/issues/1143 is eventually taken care). I am also thinking I should have opened an issue here first, to discuss the feature and added permission, so that this stuff doesn't seem like its coming out of left field. Oh well, a little late now. :\ I'll rename this issue and leave it open for that purpose.

I will have to give this permissions situation some more thought. I can leave it as it is (request trust), remove the feature and permissions (no trust required), or maybe split the feature into a separate apk/app ("Suntime Calendar".

> btw, I think a "proper" backdoor would probably require `network`
> permissions ;) .. That is a permission that will never be added.
>> Ah okay. I don’t know Android well (I’m a Unix expert), so that
> is non-obvious.

I would really hate to be wrong about that. I am suspicious of app permissions, but what makes me really suspicious is permission combinations. I refuse to install many apps because they have the capability to do more than advertised. The `calendar` permission to steal your data, and the `network` permission to phone home and report.  While I don't think these are necessary malicious, their capability makes them difficult to trust.

**Comment by pan2003** [comment]
> seriously considering removing the Calendar integration

Sounds good. IMHO, Calendar integration feature is really useless.

**Comment by forrestguice** [comment]
Its debatable, but IMHO ditto for calendar apps and scheduling in general. ;)

I don't like the permissions so I've moved the calendar integration into an [add-on](https://github.com/forrestguice/SuntimesCalendars). 

The integration is made possible by a content provider added in `v0.10.0`. https://github.com/forrestguice/SuntimesWidget/wiki/Interfaces

**Comment by forrestguice** [comment]
It is done. v0.10.0 is now tagged, probably on F-Droid within a week.
