### ISSUE TITLE
get the location in an airplane have crashed the application

### ISSUE THREAD

**Issue by codati** [forrestguice/SuntimesWidget#243]

**Comment by forrestguice** [comment]
Thank you for letting me know. I think this is a validation issue with the altitude field. I'm able to reproduce it by manually inputing a very large value.

**Comment by forrestguice** [comment]
This should be fixed in v0.9.2. It will be on F-Droid sometime next week.

The crash happens because of a silly off-by-one error when validating the altitude - the max value is 11000 meters **non-inclusive**, woops. The supporting library throws an exception when values are out of range - to avoid it values are clamped.

btw if the intention is to get sunrise/sunset on the ground below, I think turning off the altitude based refinements is a good idea. It seems official sources are reporting times at sea-level, regardless of the local elevation.
