### ISSUE TITLE
UI, Light theme, Colors

### ISSUE THREAD

**Issue by ghost** [forrestguice/SuntimesWidget#264]
Light theme of the application is great, but some colors are hard to read.
1) Yellow on white (sunrise times),
2) Light gray on white (current date).

Could you alter these colors for light theme? Or maybe make the text bold/bigger? Or allow the user to change the application colors (you allow this for the widgets, but not for the application)?

**Comment by forrestguice** [comment]
> Could you alter these colors for light theme?

Yes, there is work for this sitting in the [default colors](https://github.com/forrestguice/SuntimesWidget/blob/defaultColors/app/src/main/res/values/colors.xml) branch, and related issue #247. I got a little burnt out staring at it. I have a theory that staring at a bad UI long enough and it starts looking better and better. First impressions are incredibly useful.

What's your opinion of this color scheme?
![activity-main0-light](https://user-images.githubusercontent.com/10246147/48219051-ae867d00-e348-11e8-9003-43866e99037f.png)

> Or allow the user to change the application colors (you allow this for the widgets, but not for the application)?



That is also planned, with experimental code hanging out in the [appcolors](https://github.com/forrestguice/SuntimesWidget/tree/appcolors) branch. I think I'll be throwing that code away though - I don't like the way it works. When compared to the widgets, dynamically changing the app theme is a little more complicated than it might appear (kludgy), and further complicated by "night mode". 

I think when this feature is eventually completed, its function will be to override the default theme - a feature that will need to be turned on (defaults off), since I'm half expecting it to misbehave.

**Comment by pan2003** [comment]
> What's your opinion of this color scheme?

Yes, now it is readable. This solves the issue!

Hm... From the other point of view, you usually use yellow color for daylight and blue for twilight: for example, at the colored bar near the bottom of the screen. So maybe you'd better use orange text for sunrise and blue text for twilight in both light and dark themes? Maybe light-orange and light-blue in dark theme and a-bit-darker-orange and dark-blue in light theme?

> to override the default theme

I think this is a low priority feature. If default themes (light and dark) are good readable, the ability for the user to tweak the colors is not that critical.

**Comment by forrestguice** [comment]
As of v0.10.0 its now possible to override the app's colors using themes.
