### ISSUE TITLE
Widget text wrapped

### ISSUE THREAD

**Issue by JonnyTech** [forrestguice/SuntimesWidget#306]
Adding a 1x1 widget to my homescreen displays text broken into two lines: 
(sorry having problems inserting image)

**Comment by JonnyTech** [comment]
![widget png](https://user-images.githubusercontent.com/3584732/55283316-fa65ad00-534f-11e9-9195-1cda7be484b8.jpg)

**Comment by forrestguice** [comment]
hrm. I haven't seen this one before :\ What is the device? Android version? 
I'll try to reproduce with the emulator and figure this out.

**Comment by JonnyTech** [comment]
Nokia 3, Android 8.0. Thanks.

**Comment by forrestguice** [comment]
I think this is a "large text" issue. I can reproduce your screenshot when I increase the "Font size" or set "Display size" to "Large" from the accessibility settings. 

I've tried a couple fixes. 
1) If there isn't enough room to display the entire line, the sunrise/sunset icon should be cropped before the text starts to wrap. It looks a little funny, but its readable. 
2) The widget text no longer scales with the Font Size setting. Not a win for accessibility. I don't think its really a problem though, since its still possible to increase the text size by using a custom theme.

**Comment by JonnyTech** [comment]
Thank you for following through with this. The font size setting was not set to large (as it annoys me at how many applications cannot handle that correctly).

Unfortunately I am unable to check your changes as I lost my phone last night (two phones actually, I am not happy!).

If I can replicate the issue once I get another device then I shall reopen this issue.

**Comment by forrestguice** [comment]
thats a bummer. sorry to hear that. :\
