### ISSUE TITLE
alarm sound fails to play from external storage

### ISSUE THREAD

**Issue by islam2hamy** [forrestguice/SuntimesWidget#326]
if i change the alarm sound with any .mp3 file or .ogg , the alarm will work with no sound .

**Comment by forrestguice** [comment]
Thanks for reporting. I can confirm it doesn't currently work. Its not implemented.

I'd actually forgotten this was possible - on my test device the default is to open the media store (system sounds; alarm/ringtone/notification). After clearing that default I'm able to select mp3 and ogg through a filemanager app (like Amaze), but afterward the ringtone label isn't updated, and later when the alarm goes off, that default sound is played. So in my case its similar but a little different (the alarm isn't silent).

Out of curiosity, and to help test - what is your Android version? How are you selecting the mp3 / ogg? A screenshot of the alarm ui right after setting the mp3 might help me understand whats happening.

**Comment by islam2hamy** [comment]
ok,
my Android version is 7 , and i select the sound using file manager app and the sound name appear good after select it .

**Comment by islam2hamy** [comment]
https://www.photobox.co.uk/my/photo/full?photo_id=501884916445

**Comment by forrestguice** [comment]
hrm. I can't seem to access that url (btw you should be able to drag and drop right into the issue), but its alright, I think I get the picture (so to speak). The mp3 name appears on the label after selecting it, but later nothing is played.

**Comment by islam2hamy** [comment]
sorry for that , but i am using mobile 

https://pasteboard.co/IgiBf4b.png .

yes ,The mp3 name appears on the label after selecting it, but later nothing is played.

**Comment by forrestguice** [comment]
I think this is fixed. It will be in v0.11.5 (probably on F-Droid sometime next week).

It turned out to be a permissions problem. The current version of the app doesn't declare external storage permissions, so attempting to play sounds from the sdcard throws a SecurityException, but instead of crashing the app swallows the exception (alarm works but no sound). I've changed that behavior - it should now fallback to the default ringtone if the selected sound can't be played for some reason.

I've also added the `READ_EXTERNAL_STORAGE` permission to the app. Its now requested when trying to change the ringtone, but you can safely ignore it if using the system sounds.

**Comment by islam2hamy** [comment]
waiting for the release,

Thank you.

**Comment by islam2hamy** [comment]
It Is Fixed,
Thank You.

**Comment by forrestguice** [comment]
I'm glad this is working now. It definitely improves the alarm clock. :) 

I only wish it worked on my older phone (Android 4.4), but the sound selection silently fails. Maybe a bug in "Amaze", I dunno. I haven't tried it with another file manager.
