### ISSUE TITLE
Full moon alarm

### ISSUE THREAD

**Issue by islam2hamy** [forrestguice/SuntimesWidget#327]
please add possibility to set alarm for full moon and new moon , with offset as days

**Comment by forrestguice** [comment]
This is added in v0.12.0 - its now up on F-Droid.

I think this feature might still be improved. The instant of the full moon (or other phase) may occur at some inconvenient time (middle of the night) - for now just be aware of that (and adjust the offset accordingly). 

It might be useful to have the ability to override the time for these alarms too.. e.g. an alarm at 6PM on the day of (or just before) the full moon. This would definitely complicate the UI (but since I'm also thinking it might be useful to have the ability to completely override the date too, there are complications abound).

**Comment by islam2hamy** [comment]
thank you for that
