### ISSUE TITLE
alarm on lockscreen warning

### ISSUE THREAD

**Issue by islam2hamy** [forrestguice/SuntimesWidget#332]
the alarm doesn't show on lockscreen , 
and i should unlock the phone to tack an action .

 it was working good on v.0.11.4

**Comment by forrestguice** [comment]
IIRC its not actually implemented, so hearing that it "was working good on v0.11.4" confuses me a little, since the notification code wasn't changed between 0.11.4 and 0.11.5. So I'm not sure why it was working then, or why it broke.. but I will look into this.

This reminds me of another lockscreen related bug - with Android 7+ the app doesn't respond to `LOCKED_BOOT_COMPLETED`, so if your phone happens to restart itself in the middle of the night, the active alarms won't be restored until its unlocked.. meaning you'll sleep right through the alarm.

**Comment by islam2hamy** [comment]
Mmm , it is now work ! 
i give the app "show on lock screen" permission , and it is done .

i think it should be given as default app permission ,
what do you think?

**Comment by forrestguice** [comment]
hrm. It doesn't seem to be a normal permission. I don't think its possible to request it, or for the app to change the setting itself. ..but maybe something could be added to `Settings -> Alarms`, similar to battery optimization, so the app warns you when its off, and when clicked opens the notification settings.

I have a guess as why it defaulted to off. In `App & notifications` -> `Notifications` -> `On lock screen`, is it set to `Don't show notifications at all`? I think that global setting means you need to grant the permission for individual apps (whitelist), while the other options require you to turn the permission off for individual apps (blacklist).

**Comment by islam2hamy** [comment]
i think it is what you say .
may be adding it to Settings -> Alarms , is a good  idea .

**Comment by forrestguice** [comment]
I've added an "on lock screen" warning in v0.11.6, but it doesn't really work too well. It detects when that setting is off globally, but fails to detect if the app has been explicitly blocked. This stuff uses private api (so a little hard to figure out), but per-app lock screen visibility appears to be controlled by a different setting (that I have yet to figure out).

Anyhow, I will leave this issue open as a reminder that the warning still needs some work.
