### ISSUE TITLE
half hour and 45-minute time zones are listed incorrectly

### ISSUE THREAD

**Issue by leela52452** [forrestguice/SuntimesWidget#346]
version 0.11.7
the error is persistent
i changed to "asia/calcutta"
unfortunately, it is showing wrongly as  05:00 IST
see https://en.m.wikipedia.org/wiki/Indian_Standard_Time

**Comment by forrestguice** [comment]
Sorry but your problem isn't clear - you will need to elaborate please.
Is the warning shown when it shouldn't be? is the time incorrect? the timezone incorrect?

What is the configured location? The warning is based on your location and is overly simple - it is shown when the difference between local mean time (solar) and the timezone is greater than 3 hours. Unfortunately there are places with some pretty screwed up timezones (e.g. China) where this check fails routinely. BTW the warnings can be disabled from Settings -> User Interface -> Show warnings.

"Asia/Calcutta" is synonymous with "IST", so this actually looks correct to me, but it should be "5:30" (instead of "5:00") during summer? The timezone list comes from your device itself, so its very possible that its out of date and doesn't reflect the most recent rules. I think that is what is happening.

**Comment by forrestguice** [comment]
hrm, it is also possible there is a bug in the app when handling timezones with a half hour offset. I need to take a closer look here. I also see an offset of 5:00 instead of the expected 5:30.

**Comment by forrestguice** [comment]
Bug confirmed - I've found the problem. Timezones with a fractional offset are being incorrectly rounded (5.5 -> 5.0). It is a silly mistake (integer division). 

So that explains the incorrect timezone. It might also explain the persistent warning, but its not possible to debug that without knowing more about the app's configuration.

**Comment by leela52452** [comment]
your conclusions are correct.
for some reason i did not received email of your comments for this issue.
it is showing correct time.
in spite of selecting correct time zone, it persists.
this how error looks like.

**Comment by forrestguice** [comment]
Thanks for the screenshot. It helps a lot!

The warning "the time zone may be wrong for this location" is actually about your location. I can see that your location is set to Phoenix (the default, which belongs to time zone GMT-7.5), while the timezone is set to Asia/Calcutta (GMT+6.5), over 12 hours difference. The warning is displayed whenever local mean time and the timezone disagree by over 3 hours (and local mean time (solar time) is determined by your longitude (its actually just GMT offset by your longitude)).

It looks like the location mode is set to "current location", but GPS is disabled. I recommend changing your location to "user defined" and manually inputting longitude and latitude of your general location. That should fix the persistent warning.
