### ISSUE TITLE
Notifications don't respect Do Not Disturb

### ISSUE THREAD

**Issue by shawn1thompson** [forrestguice/SuntimesWidget#369]
In Suntimes Alarms, notification sounds don't respect Do Not Disturb settings. I've set the type to Notification. Also, the notification sound seems to take over the audio; so, if I have music playing and the notification appears, my music won't start playing again after the notification sound until I dismiss the notification. Thank you.

**Comment by forrestguice** [comment]
Thanks for reporting. I hope this didn't cause a scene (like that one time I left the ringer on at the climbing gym..)

At the moment its unimplemented. The sound/vibration is played independently of the notification itself (to overcome bugs in earlier Android versions), but that is missing a check on the "do not disturb" settings. I basically missed this detail since I'm still on a much older device. It seems "Do not disturb" was added in api21 (and then behavior changed again in api23). I'll fix this in v0.12.2.

The notification sound taking over the audio might be because the app is still using older api (instead of creating its own notification channel). Unfortunately I think changing this behavior is blocked by #122, but I'll take a closer look to see what can be done.

**Comment by shawn1thompson** [comment]
"Thanks for reporting. I hope this didn't cause a scene (like that one time I left the ringer on at the climbing gym..)" LOL, it didn't.

Thanks. I'll look forward to the next version.
