### ISSUE TITLE
feature request. large font option

### ISSUE THREAD

**Issue by nutpantz** [forrestguice/SuntimesWidget#383]
While phones are getting bigger, there is more to put on the screen sat one time, which usually ends up having entering l everything smaller..
It would be nice if there was a font size option to make things easier to read.

**Comment by nutpantz** [comment]
Or let the widgit grow larger then the icon size.  (Ie my screen is 7x8 but no matter how large i resize the widgit it's never bigger then 2x1 or 1x1b icons)

**Comment by forrestguice** [comment]
The widgets used to respond to Android's "large text" accessibility option, but at some point it was disabled because it wasn't displaying consistently. The workaround is to create and apply a theme with larger font.

![Screenshot_2020-01-12-13-02-07](https://user-images.githubusercontent.com/10246147/72224939-eab10100-353c-11ea-9e14-9e711741772d.png)

It sounds like that isn't what you are getting at though. It sounds like you want really huge text and icons to match. So similar to the clock widget where the text size increases to take up available space. I can see in that previous screenshot no matter how large the text is (32 is current max) the icons are always tiny.

**Comment by nutpantz** [comment]
Yes exactly
