### ISSUE TITLE
Inconsistent moon illumination numbers

### ISSUE THREAD

**Issue by sjvudp** [forrestguice/SuntimesWidget#384]
I noticed that the moon illumination percentage differs significantly between main screen and moon details:

Main screen says "1% illuminated" (in German):
![Suntimes_20191224-205521](https://user-images.githubusercontent.com/6734808/72222256-f57e8c80-3562-11ea-99a1-c2596b34fb31.jpg)

Detail screen says 2.2% illuminated (in German):
![Suntimes_20191224-205531](https://user-images.githubusercontent.com/6734808/72222258-f8797d00-3562-11ea-992c-676c0ba8ef68.jpg)

Both screen shots were taken within a few seconds. Obviously one of the numbers cannot be correct.

**Comment by sjvudp** [comment]
Ooops, quite confusing. Would it be hard to add the time of lunar noon (like instead of "1% illuminated" use "1% illuminated at HH:MM")?

**Comment by forrestguice** [comment]
Sounds like a sensible idea. The main table could display "at HH:MM" and the dialog could display "right now". At the moment the lunar noon info isn't available at all, its missing from the UI, so this would fix both problems.

As to how hard.. well I've got some perfectionist tendencies so its probably "impossible" without aggravating existing problems like #207. Maybe if the "illuminated" was dropped (its implied) there might be room for lunar noon without pushing it onto a new line.

**Comment by ericjs** [comment]
I'm not sure if I should file this as a separate issue, but it seems related: on the main page, yesterday (29 Nov 2020) it showed Waxing Gibbous, 100% illuminated, and swiping to see the info for the next day (30 Nov 2020) it showed Full Moon, 98% illuminated. It would seem that the text description of the mood phase and the % illumination aren't either based on the same lunar noon assumption, or one of the calculations has a bug.

**Comment by forrestguice** [comment]
Confusing but probably not inaccurate. The "Full Moon" label is applied to the entire day but the full moon is actually an instant, so its never going to be "Full Moon 100%" unless the time of the full moon coincides with lunar noon. So "Waxing Gibbous 100%" is expected if lunar noon and the instant of full moon are close to each other but on different sides of the dateline.

In your example, lunar noon on the 29th is very close to the full moon, but the instant of the full moon actually occurs on the 30th. Likewise, lunar noon on the 30th occurs after the instant of the full moon, but the day is labeled "Full Moon" because its the date that contains that instant.

**Comment by ericjs** [comment]
I see. I would suggest that for both what I reported, and for what OP reported the common cause of dissonance is the lunar-noon-based element, and would suggest that this is also the least intuitive or useful, as most people aren't thinking about lunar noon. One alternative I can think of would be reporting the range of %ages that occur across that day, so it might be 96-100% on Nov 30th and maybe 97-100% on Nov 29 (only reaching 100% by rounding? really 99.something?) Just a thought. This doesn't seem completely satisfying to me either, but it at least ameliorates the 100 / Gibbous conflict.

You might also consider doing some kind of rounding for the moon phases. From an intuitive standpoint, people don't think of the full moon as being a mere instant, there is a certain range of "close enough" where we look at the moon and consider it full. 

(It's amazing how functionality that seems so simple on the surface quickly raises so many complexities...)

**Comment by forrestguice** [comment]
Its an issue of picking a single daily illumination - lunar noon was originally chosen because that is when you'll actually see the moon and benefit from its illumination. Displaying a range is something to consider. I think putting an @ <time of lunar noon> as previously discussed might be sufficient. We might also report some other value (maybe rising illumination). 

We could fudge the numbers a bit too - on the days of the primary phases we display the illumination at those instants, and lunar noon on the other days. That would avoid a "Full Moon 98%" (not something people expect to see), but preserve "Waxing Gibbous 100%" (which is technically accurate).

These are the values reported by the underlying library - despite what might seem intuitive they are technically instants. Labeling the entire day (a calendar convention) I think reinforces misconceptions. The "full moon" by a "full appearance" lasts anywhere from 2 to 3 days. This is the way I thought about it before I started down this rabbit hole. ;)

Anyhow, thanks for your comments. I appreciate the feedback. This is definitely something to be improved.
