### ISSUE TITLE
Times of sunset unreadable on any non-english version

### ISSUE THREAD

**Issue by verdulo** [forrestguice/SuntimesWidget#43]
I've checked on 2 phones (with smaller and bigger screen) and times of sunsets and solar-noon go out of the screen on both Polish, Esperanto and German translations. What can be do to fix it:

1. Shorten the strings "sunrise_short" and "sunset_short", eo/pl versions are ready, now @HerHde needs to update German translation.

2. The date is currently displayed in 2 lines "Today |next-line| 2016-08-16", maybe in similar way display the column "Rise" and "Set" - display the icon of Sun above or in the next line.

3. There's lots of unoccupied space between a date and the word "Rise", so maybe align the column "Set" to the right corner of screen, and make width of column "Date" variable.

**Comment by HerHde** [comment]
Yeah, this is a bit difficult.
We don't have a rise and set in German, I could write "Auf[gang]" and "Unter[gang]" which means "up" and "down", but this is too ambiguous so I've decided to use "morning" and "evening", even if it is not so short:
```diff
-  <string name="sunrise_short">Aufgang</string>
+  <string name="sunrise_short">Morgen</string>
-  <string name="sunset_short">Untergang</string>
+  <string name="sunset_short">Abend</string>
```
If there is any german user with a better proposal, just write it ;-)

**Comment by forrestguice** [comment]
All good suggestions. I will look into fixing it - changing the layout might be a better fix than changing the strings.

I just discovered I can preview the locale in the android studio design tab - I can see what you are talking about, especially for the smaller screens. The entire sunset column is bumped just out of view :\

**Comment by forrestguice** [comment]
ok, I think the situation is improved. I have put some constraints on the column headers so no matter how long the text those fields shouldn't push other content off the screen. For smaller screens it should ellipse (...) the cutoff portion of the text, and for larger screens the constraints should relax to allow the table to take up more space.

preview (nexus one .. 3.7" screen)
![prev1](https://cloud.githubusercontent.com/assets/10246147/17985582/52ebc272-6acb-11e6-94fe-9964e2b897e4.png)
![prev4](https://cloud.githubusercontent.com/assets/10246147/17985688/c288848a-6acb-11e6-8e69-526c42ecd9dc.png)

preview (nexus 6 .. 6" screen)
![prev2](https://cloud.githubusercontent.com/assets/10246147/17985646/8fe1589a-6acb-11e6-86fa-4182c542ef3c.png)
![prev3](https://cloud.githubusercontent.com/assets/10246147/17985665/ac00517a-6acb-11e6-990f-010e1c938d58.png)

an alternative ..  I think this looks a little awkward, but we can also allow the labels to use two lines instead of one. 
![prev5](https://cloud.githubusercontent.com/assets/10246147/17985701/d2c463f0-6acb-11e6-98d4-a58f1d0db97c.png)

thoughts?

**Comment by forrestguice** [comment]
I am also thinking a "ui setting" here wouldn't be a bad addition - labels display as either "text", "icon", or "text + icon".

**Comment by 9662** [comment]
Not a Polish speaker, though I can understand some. With that said, the two line version looks terrible to me because the words are broken in the middle of a syllable (the -chód in there is a single syllable).

FWIW, I suppose an icon-only preference is one possible option. 😃
