### ISSUE TITLE
No way to remove London as default location

### ISSUE THREAD

**Issue by johnro76** [forrestguice/SuntimesWidget#430]
Steps to reproduce.
Install app
Set a location (London doesn't appear in Manage Places until after I pick a location)
Go to Manage Places, delete London
Go to home screen to place a widget
Choose any of the Suntimes widgets, place it somewhere on screen
Observe that London is in the location
Cancel the widget
Go back into Suntimes app, go to Manage Places
Observe that London has been added again

App version: 0.13.0
Expected behaviour: if I add a place and remove London, the place I added should become the default.  Alternatively there should be a way to mark a Place as the default.  In any case, if the user removes a place I think the app shouldn't add it back in.

Device: Samsung S7 Edge
Installed from f-droid

**Comment by forrestguice** [comment]
The way it currently works is the location list starts completely empty, and the app, widget, alarm, whatever, start with the default location (provided by the locale). I think the undesirable behavior happens whenever the location dialog is opened - it tries to add the value it finds there to the list. So I htink what is happening is London is getting removed, but then readded the next time you bring up any configuration  (app, widget, alarm, etc).

There is no configurable default location (and no plans to add one), but I can see how explicitly deleting something and having it reappear would be annoying. As a workaround, you need to change the configuration of all your widgets, alarms, etc, because the place will continue to be readded as long as its being used.

**Comment by forrestguice** [comment]
Maybe an easy fix is to make whatever location the app is currently using the default that gets inherited by widgets and alarms, while only the app itself starts with locale default. This would prevent the constant reintroduction of the locale default every time a new widget is created. ..but attempting to remove a value from the list will have the same effect though - its just a list, independent of any individual configuration, and locations aren't actually referenced, they are copied by value - any location in use will be eventually copied to the list (triggered by the dropdown).

**Comment by forrestguice** [comment]
By the way, thank you for reporting this. I appreciate it.
It should be patched with v0.13.1 (probably a week or two out).

**Comment by johnro76** [comment]
Thanks for responding and actioning this so quickly.  I think "make whatever location the app is currently using the default that gets inherited by widgets and alarms" is an elegant solution.
