### ISSUE TITLE
[bug] "User Interface" is repeated multiple times in UI settings

### ISSUE THREAD

**Issue by rchintsov** [forrestguice/SuntimesWidget#434]
Just found that heading "User Interface" is repeated multiple times in UI settings.
App version is 0.13.0, Android is 6.0.1.
How it looks:

![Screenshot_repeated](https://user-images.githubusercontent.com/32958827/95919353-186df380-0db6-11eb-9a3d-c989ae73382b.jpg)

**Comment by forrestguice** [comment]
The repetition of the "User Interface" title is actually intentional, since it scrolls for over a page, but those groupings could be better. I think "blue hour" and "golden hour" should belong to the group above it. 

Lets reorganize these. As you suggested in your other comment, moving the "Solstice Tracking" option next to "Show Solstice/Equinox" makes sense.

**Comment by rchintsov** [comment]
Do you have the ability to change (rename) these headers individually?

**Comment by rchintsov** [comment]
We can just build a graphical schema with all setting options firstly to imagine what the app already contains and secondly to rework and discuss this in more interactive way.

To create schemas I prefer the [app.diagrams.net](https://app.diagrams.net) (formerly draw.io) - a simply app for drawing that can work with GitHub directly and can make commits. It's require to connect with your GitHub account (it works like an external app), but it's just a few clicks.

So, if you don't mind all of that, I will create a common repository for schemas that we'll can work with.

**Comment by forrestguice** [comment]
These are defined in [/res/xml/preference_userinterface.xml](https://github.com/forrestguice/SuntimesWidget/blob/master/app/src/main/res/xml/preference_userinterface.xml). The group titles can be changed by modifying the `android:title` attribute, or removed entirely by removing or reorganizing the `PreferenceCategory` tags. The other pref screens are nearby (same directory). It is only important that the `android:key` attributes remain unchanged, otherwise these can be shuffled around however.

I'm not opposed mapping it all out first if you want to host that repo. Modifying that file directly (repeated trial and error) also works for me.
