### ISSUE TITLE
Why is my widget constantly off-sync and lagging behind 

### ISSUE THREAD

**Issue by JrJen** [forrestguice/SuntimesWidget#459]
So I've been using this app for a while now and on my new phone the widget does not update time. It lags behind the actual clock and sometimes gets stuck for like a day. I tried:

- Reinstalled an older Version (I get it via Aptoide Store)
- Disabled any power-save options that might kill it in background. Auto-Start set to ignore. 
- Different launchers (Huawei Start/Nova launcher) 
- Enabled the upcoming alarm notification for 12 hours ahead. Since I set a lot of alarms, Suntimes is now constantly up in my notifications - I thought that might force that Suntimes is awake and updating the widget. Did not work unfortunately. 

I noticed: 

- The alarms still work fine and can wake the screen 
- Even if I tap on it to launch the app the widget doesn't update, It's always off by hours.
- It mostly gets stuck during times where I don't wake my phone for a few hours, I still suspect some power-save options causing the issue. But I had multiple huawei phones with those aggressive power-save settings before and used suntimes without those problems. I have no idea what I'm missing here, there must be some setting or problem on my device preventing the update and it's really annoying. I tired to fix it myself but now I need some advice. 

Here is my app version and a screenshot of the widget 

![Screenshot_20201201_132407_com forrestguice suntimeswidget](https://user-images.githubusercontent.com/75312763/100742903-c885d300-33db-11eb-81e3-53e9532cdaf2.jpg)

![Screenshot_20201201_131733_com teslacoilsw launcher](https://user-images.githubusercontent.com/75312763/100742976-ef440980-33db-11eb-929a-3344dc34b977.jpg)

Thanks in advance

**Comment by JonnyTech** [comment]
I know that you say that you have disabled power management, but Huawei devices do have very aggressive battery optimization features.

Try following [this guide](https://support.doubletwist.com/hc/en-us/articles/360001504071-How-to-turn-off-battery-optimization-on-Huawei-devices) and select the suntimes app - don't forget the power-intensive prompt settings too.

**Comment by forrestguice** [comment]
It does sound like a battery optimization issue. The widget updates have been a problem in the past but have since been working reliably. However I think once a widget update fails once, it still loses future updates (becomes stale), until explicitly triggered again.

The workarounds you listed are interesting. Unfortunately none of them trigger the widgets in the way you are thinking. You can force all of your widgets to update by going to `Settings -> Widgets`. Selecting and resizing a widget should also trigger an update. You can also reconfigure the click action to "update widget" instead of launching the app.

I think having the click action always trigger an update (in addition to whatever its doing) is a good idea - this would allow misbehaving widgets to recover quickly. As to why its misbehaving I'm not really sure, but I intend to try simulating aggressive battery optimization, and maybe find a more robust way to schedule the updates.

btw, which widget is it? The scheduling is slightly different for each. The "clock widget" is by far the most aggressive (per minute). I ask because I don't recognize any Suntimes widgets in your screenshot (the digital clock looks like mine, but I don't remember including the date - maybe its just been configured with a title?)

**Comment by JrJen** [comment]
Thanks for the replies. I was able to deactivate all power save features, even the intrusive ones as  shown in the guide.

I am using the 3x1 clock with the title %dD, %d I put in so I reads out the date. 
![Screenshot_20201202_121722_com forrestguice suntimeswidget](https://user-images.githubusercontent.com/75312763/100866195-99816700-3498-11eb-8dda-15cc2b6ab385.jpg)

I set the widget action to update the widget as you said, this seems to be the most obvious fix. If it was possible to update the widget AND open the actual app on tap action it would be perfect.

While that's not here I found .SuntimesConfigActivity2_3x1 and made a button with a shortcut creator to instantly take me te to that widgets settings, which should also update. 

**I haven't had the clock get stuck today so that seems like a success!** 

BTW, my phone has a weird UI that has to conform to its screen, so this isn't the only app which looks a bit off. The date/title is in no man's land and rezising the widget (does update it) causes other issues. My phone re-scales the widget all the time to keep it in the center. It's bizarre but it's really the phone deciding a new size; It's a Huawei Mate Xs (foldable) so every time I unfold the phone it turns the 3 x 1 into a 7 x 1 widget to force that it stays in the center/relative to how it was folded. Here's how this looks open vs. closed as I showed before. 

![Screenshot_20201202_121749_com teslacoilsw launcher](https://user-images.githubusercontent.com/75312763/100867230-2ed12b00-349a-11eb-9037-40959526f5bb.jpg)

As you can see it went ahead and stretched the widget, all while cutting off the bottom. Also moved the date (title) far out, which doesn't seem anchored to the rest of the clock. 

Since this is a ridiculous phone that nobody buys I don't think that suddenly changing screen size and resolution/grid scale is a normal use scenario. It's still interesting to see how it deals with the UI, maybe you find some useful input in my posts.
