### ISSUE TITLE
Alarm: turning off after screen is off

### ISSUE THREAD

**Issue by kamilmaj** [forrestguice/SuntimesWidget#470]
I am using alarm with vibration only. 
Alarm is lightning the screen and showing the Alarm screen amd vibrating but after a while when the screen goes off after few seconds, vibrating stops. After click something you csn see alarm screen with dismiss snooze option but not vibrating.

**Comment by forrestguice** [comment]
Thanks for reporting this. This is the kind of thing that causes one to sleep through their alarm.. not good.

I just tried an alarm with vibration only with the same result. The problem seems to be isolated to vibration. If I assign a ringtone the sound continues after the screen goes off (but the vibration stops).

**Comment by kamilmaj** [comment]
I will use Alarm instead of stock one when this issue will be resolved :)

**Comment by forrestguice** [comment]
This should be fixed in v0.13.7 (probably on F-Droid next week). 

I'm not sure why repeating vibrations are stopped - the process / notification continues running. The fix (workaround) was to use a Handler to manually loop the vibration (instead of passing the `repeat` flag).

Let me know if it misbehaves. The vibration may be cut short when the screen turns off, but it should start again immediately.
