### ISSUE TITLE
How to use custom actions?

### ISSUE THREAD

**Issue by ghost** [forrestguice/SuntimesWidget#489]
Where can I find a documentation on using custom actions?

I want to activate Do Not Disturb mode at a specific time.

**Comment by forrestguice** [comment]
Here's some documentation aimed at developer; https://developer.android.com/reference/android/content/Intent .. The custom actions just exposes this api, allowing users to create and trigger their own intents. 

However, I'm not entirely sure its possible to trigger *Do Not Disturb* via intent. This is something to be researched.

What is possible is to launch a specific app, or to trigger a specific action supported by that app. Another possibility is to allow the system to choose the app - this is what happens when the Intent has fields that are blank (referred to as an implicit intent). For example, an Intent with an Action `android.intent.action.VIEW` and Data containing a geo uri (e.g. geo:33,-112" will trigger the default map app at the given coordinates. To launch a specific app (instead of letting the system choose) we need to fill out the Class field. 

You might try "Intent Intercept" available on F-Droid (https://f-droid.org/en/packages/de.k3b.android.intentintercept/). Its useful for exploring the Intents offered by various apps. Otherwise the only way to know about them (and what is possible) is to find official documentation. Hopefully the DnD functionality has been exposed this way, otherwise you might be out of luck.

**Comment by forrestguice** [comment]
Supposing *Do Not Disturb* can't be triggered with intent, it should be possible to get this done by writing a custom app that responds to an Intent and triggers it for you. Its possible to trigger *Do Not Disturb* with `NotificationManager` but requires special permission (https://stackoverflow.com/questions/31862753/android-how-to-turn-on-do-not-disturb-dnd-programmatically).
