### ISSUE TITLE
Quite a few custom theme settings not working

### ISSUE THREAD

**Issue by Gitoffthelawn** [forrestguice/SuntimesWidget#492]
Thank you for the great app and for making it open source!

It's really wonderful, but I found many of the strings in the app to be too tiny to easily read.  Also, I found the contrast to be too low.  As such, I created a nice custom theme for it.

Unfortunately, many of the theme settings do not get applied, and others *appear* to not get applied because they require the app to be completely closed and restarted.

For example, the font size options appear to do nothing in the app.  Also the main background color does not change when the background color in a custom theme color is changed.

Things like settings for the color of the day/night bar in the bottom of the main screen do not become effective until the user forces the app the restart.  Also, the previews for that element do not reflect the colors specified in the custom theme.

I have some other constructive feedback as well, but please let me know if you have time to work on things or would prefer I hold off on other issue reports.

Overall, I find the app fantastic, but I need almost everything to be significantly larger to make use of it.  Allowing the main window to scroll vertically would be a big help in this regard too.

Thank you again for the wonderful app.

Tested v0.13.9 on Android 7.0

**Comment by forrestguice** [comment]
Thanks for the feedback. Its appreciated. :)

You've hit on a lot of the limitations - the theme system was actually designed and intended for the widgets, and its application to the app itself an afterthought. In this respect the app only applies the foreground colors, and you must restart it for the settings to take full effect. For technical reasons I don't think this is unreasonable, but we might show a message immediately after switching to a custom theme to make this clear.

As noted the font sizes aren't applied in the app. I can look into using these though (at least to the main page).  I can understand the issue with the text being too small. A workaround is to check "Large Text" from your accessibility settings - the app should respect these settings (and correctly display the larger text). Unfortunately its a global setting - all the text in all your apps will become huge.

Please feel free to leave more comments, or nitpick the details, etc. While I can't promise when I'll be able to work on these (development occurs in spurts), this sort of feedback is very helpful when I do. You are the first to report your experience with the themes (as applied to the app) - its fun for me when I discover people are using these features. Its a great motivation for improving them.

**Comment by forrestguice** [comment]
btw, I'm interested in including additional default themes, if you'd like to share your color scheme.

I don't think picking colors is easy, especially when accessibility is taken into account. The current schemes were checked with a tool for contrast, but I think in some cases its marginal. The app could probably use an extra high contrast theme.

**Comment by Gitoffthelawn** [comment]
Thank you for your wonderful reply.  I've learned to check with others before giving unsolicited feedback to make sure it is welcome. :)

I'm new to this app, so I have the temporary advantage of noticing issues likely not obvious to someone more experienced with it.  I'll write back with more details as time permits.  Would you prefer individual issues for each topic, or a single thread?

Regarding the theme I created, yes I am happy to share it with you.  I'm over-educated and have much experience when it comes to visual stimuli, so I can be a good resource to talk with regarding focus/acuity/color/contrast/size/shadow/range/movement issues.

I've also been saving some screenshots for you of various issues as I notice them.

BTW, if you haven't checked out TerraTime, it's worth a peek.  It's not open-source, and I think it's only available via Google at this time.  The URL is: https://play.google.com/store/apps/details?id=com.daylightclock.android

It suffers from *smallfontitis* as well, but where it really shines is some of its graphical representations of data.

**Comment by forrestguice** [comment]
The text settings are now applied in https://github.com/forrestguice/SuntimesWidget/commit/9a948a590ff64c25e1888b6f89e0c436ead1e411. Its a step in the right direction I think. Here's the "Large Text" effect duplicated with a theme.

`title: 16 (bold), text: 15, time: 15, suffix: 14`

![Screenshot_2021-03-18-10-24-40](https://user-images.githubusercontent.com/10246147/111669855-72933a80-87d4-11eb-9f8e-cbf92ccff05e.png)

It may introduce a few problems. Selecting from the default widget themes results now results in very small text - these work for a widget but not the app. I'm thinking of just hiding these so that menus in `Settings -> User Interface` only show `[default]` (until a user defined theme is added). I'm not sure listing these was useful to begin with - its an artifact of the way its implemented - `[default]` and `Dark` are not the same thing. Selecting a theme is actually an override on individual views in the layout. The default is to leave things as they are (as defined by layouts, styles, etc).

> I'm new to this app, so I have the temporary advantage of noticing issues likely not obvious to someone more experienced with it. I'll write back with more details as time permits. Would you prefer individual issues for each topic, or a single thread?

I'll leave this up to you. I'm not terribly picky about the way this tracker is used. It may be more convenient to keep everything in a single thread. I will create and link additional issues if I think it makes sense when composing the changelog.
