### ISSUE TITLE
[Feature request] planetary new year/spring/summer/fall time

### ISSUE THREAD

**Issue by akostadinov** [forrestguice/SuntimesWidget#525]
Would be real nice to have time when Earth enters winter/spring/summer/fall. Only yesterday I realized that this is a planetary event and is not directly related to midnight local time as we are used to think.

So I'm asking fir such a feature.

**Comment by forrestguice** [comment]
hrm, I'm not sure I understand. Aren't these the solstice and equinox date/times?

Those are 'planetary' in that its the same moment everywhere (isn't offset by longitude), although whether its labeled summer vs winter, or spring vs fall, depends on hemisphere. The "vernal equinox" is defined as the spring equinox in the northern hemisphere and marks the beginning of spring, and the start of the "sidereal year".

By this definition, its only winter as of yesterday. I think meteorologists define it differently though (seems kind of arbitrary; they say spring is march 1 vs march 20). I think its also slightly different if trying to observe these events at some physical calendar (whether the "event" takes place 'today' vs 'tomorrow' with respect to sunrise).

Anyhow, I would definitely like to improve the way the app displays progression through the seasons. It feels like like I'm lacking insight though.

**Comment by akostadinov** [comment]
Oh, wow. I now saw it. Yesterday I didn't notice it. So that's great. Thank you!

wrt the UI, you can show seasonal progression like the sun bar.

**Comment by forrestguice** [comment]
I guess a simple horizontal bar is an option. A track in the shape of an [analemma](https://en.wikipedia.org/wiki/Analemma) might be interesting too.

**Comment by akostadinov** [comment]
I can't imagine how it would look. In either case I'm happy I can see the times already :)

**Comment by gdt** [comment]
In the US the NWS defines meteorological winter, December 1 to February 28, and I am pretty sure those are each in the forecast office's timezone.   But these are fixed calendar definitions and I don't think it makes sense to add them into Suntimes.

I am actually 99.9% happy with Suntimes and seasons, with the solstice/equinox view and days from and days to.  Now I can see the time to previous, which is more interesting the day after the solstice than days until equinox.

It might be nice to always show the previous event and the next 3 for starters and then scroll, rather than fixed by year, but it is so easy now that I don't really think that's worth it either in coding time or in terms of user confusion.

**Comment by forrestguice** [comment]
> It might be nice to always show the previous event and the next 3 for starters and then scroll, rather than fixed by year, but it is so easy now that I don't really think that's worth it either in coding time or in terms of user confusion.

Interesting suggestion. Displaying it like this makes a lot of sense to me. Unfortunately it wasn't written that way (probably not an easy hack). I've been wanting to extend this dialog though, so I'll remember this if/when its eventually rewritten.
