### ISSUE TITLE
how to use Actions?

### ISSUE THREAD

**Issue by treasuretron** [forrestguice/SuntimesWidget#546]
I see there are a couple actions like open the calendar... but I was thinking it would be nice to open a weather app on tapping one of the widgets. What should I put for Action and Data? Any chance to get some more documentation on this or be pointed to where it exists? Thanks!

EDIT: just realized hitting the question mark on the actions page suggests reading up at https://developer.android.com/guide/components/intents-fliters but that's giving me a 404...

**Comment by forrestguice** [comment]
Hi. It looks like there's a typo in that url; its https://developer.android.com/guide/components/intents-filters (it'd probably be helpful if the apps showed a live link instead of having to retype it). This is an advanced topic though. The linked documentation is aimed at developers.

Opening a weather app (or any app) should be straightforward. You need to build an explicit Intent that launches the app - the important field is `Class` - it needs to point to the activity you want to launch. If you omit this its an implicit intent, and the OS gets to decide what should happen. The map and calendar apps are launched this way (the system decides which).

You'll want some utility that shows package info for installed app; something like https://f-droid.org/en/packages/com.oF2pks.applicationsinfo/ .. This utility might be useful too; https://f-droid.org/en/packages/de.k3b.android.intentintercept/,

**Comment by forrestguice** [comment]
@treasuretron I was curious if you had any luck with this?

I'm trying to improve the documentation, so I've added a [section](https://github.com/forrestguice/SuntimesWidget/wiki/Help#actions) to the project wiki, and a link to that from within the app. It adds a useful link, 'Common Intents', but otherwise its not (yet) much of an improvement. I was thinking a few practical examples might go a long way, e.g. opening some app's activity, opening a link in a browser, etc.

Anyhow, the next patch release `0.14.1` should automatically close this issue, but I'm still interested in feedback if you have any.

**Comment by treasuretron** [comment]
hmm, unfortunately no luck. I've configured the action as shown. When I tap the widget it goes to the widget settings screen. Thanks for updating docs though!

![Screenshot_20220224-175304](https://user-images.githubusercontent.com/679113/155621381-90853fa2-5994-4f0a-9e74-8654b893e1f1.png)
![Screenshot_20220224-175457](https://user-images.githubusercontent.com/679113/155621383-52aa1a19-99a0-4a8d-96cf-baaf9f8baee0.png)

**Comment by forrestguice** [comment]
> When I tap the widget it goes to the widget settings screen. 

That is the fallback when the intent fails to launch - I'm guessing the `Test` item also shows "Failed to start activity".

I think I see the problem though - I think the `class` field is case sensitive, so `.Activity.MainActivity` vs '.activity.MainActivity` is enough of a difference to cause it to fail.

**Comment by forrestguice** [comment]
> hmm, unfortunately no luck

To my chagrin, I've discovered a bug that causes most explicit intents to fail, so its no wonder this didn't work for you. 
I'm sorry for any time wasted on this. :\

It should be fixed in `v0.14.4`, with an additional field, 'Package", that should contain the target app's package name (this value also gets repeated in the class name). e.g. the package name would be `com.ominous.quickweather`, and the class name `com.ominous.quickweather.activity.MainActivity`.

**Comment by treasuretron** [comment]
thanks for the info, will take a look at the actions! Firstly I just want to get the widgets looking right again so I've commented on an existing issue and will open another now. Thanks!!

**Comment by forrestguice** [comment]
A last minute addition - the button to the right of the package field should offer suggestions. These are the packages/activities that are visible to the launcher.

Its a nice feature that I expect to break in the future - the latest OS versions treats this information as sensitive (so its possible, depending on OS behavior, that the list is practically empty).
