### ISSUE TITLE
High battery usage in background

### ISSUE THREAD

**Issue by Git-Forked** [forrestguice/SuntimesWidget#575]
High battery usage in background reported by device, suggests to sleep the app. 
Please fix.  An app with battery drain is not good.

**Comment by forrestguice** [comment]
I don't experience this issue, but I will make an effort to reproduce it. You can help by providing necessary details.. Please provide app version, a screenshot of battery use, and a description of your use case.

There shouldn't be any background activity (outside of rescheduling alarms on reboot). In the past there was a bug that caused the notification service to continue idling though, so that is where I'll look first..

**Comment by forrestguice** [comment]
I've found what is likely the cause. Is your primary use the alarms feature? 

> a bug that caused the notification service to continue idling

It seems its the same sort of thing. After scheduling an alarm (upon showing the 'upcoming' notification) the service fails to stop itself. Its runs (doing nothing) until the alarm is eventually triggered or dismissed. It is stopping itself after reboot (which is where this bug was before). 

There were changes made to the service recently (v0.14.0) to support power off alarms. I'm guessing one of those is responsible for breaking it.

**Comment by Git-Forked** [comment]
> What I mean by this is, how are you using the app? Do you have a screen full of widgets? If so which ones? Do you use alarms and notifications? one alarm? many alarms? How about the world map dialog?

I only have 1 widget, weather.  I have no alarms set.  I do not use world map.

> That is frustrating.. especially when I've been told to "please fix" (in my opinion this is kind of rude).

It was not rude.  It prompted you to find a bug and fix it, improving your code.  That seems worthwhile to me.

> So I don't know if its actually fixed or not. Hopefully it was just the device detecting an idle service (now fixed). If anyone else sees a battery warning, please comment with some details.

Thank you for fixing the idle service.

**Comment by forrestguice** [comment]
`It was not rude. It prompted you to find a bug and fix it, improving your code. That seems worthwhile to me.`

I am telling youit is rude. You don't get to dictate my opinion.

It did prompt me to find the bug, but that is because I care about the quality of the app. If you also care, you can take more than 3 sentences effort (one demanding that I fix it). That advice applies to any projects you might care about.

**Comment by Git-Forked** [comment]
I stopped using your app, so I don't care if it works anymore.  Don't bother replying to me again.
