### ISSUE TITLE
[Feature request]  Ability to add alarm before event

### ISSUE THREAD

**Issue by saiful117a** [forrestguice/SuntimesWidget#586]
Hi guys I'm new to github. I create an account just because I like Suntimes very much. I would like to see Suntimes with the ability to set alarm before specific event. For example, set alarm 30 minutes before morning astronomical twilight (start). Thanks.

**Comment by forrestguice** [comment]
>  because I like Suntimes very much

I'm glad you like it - thank you for the kind words.

> the ability to set alarm before specific event

You are in luck because this feature already exists. It seems to be hard to find though - you aren't the first to overlook it. I'm looking for ways to improve this.

From the edit page (after the dialog that selects the event/time), click on the button `at`. That should display an "Alarm Offset" dialog. Another way of getting there is by clicking the overflow menu `:`, then `Options` -> `Set Offset`.
