### ISSUE TITLE
sun position is out of alignment

### ISSUE THREAD

**Issue by treasuretron** [forrestguice/SuntimesWidget#601]
**Describe the bug**
Ever since I've changed timezones (US eastcoast to central Europe) the daylight hours has been bumped over to the right (see screenshot). The sun is in the right position if the day below it was oriented correctly but it is skewed.

There is also a message on the main screen of the app which reads, "The time zone may be wrong for this location." I tap "SET TIME ZONE" and the one listed is correct so I tap "SET". The message is still at the bottom...

**To Reproduce**
1. Go to Europe
2. Sunposition graph changes but sun is in the right place.
3. delete widget and re-add, same behavior.

**Expected behavior**
adjust the graph based on local daylight hours.

**Screenshots**
![Screenshot_20220515-132010](https://user-images.githubusercontent.com/679113/168470361-15b7c787-1615-4d06-beaf-e999cb918419.png)
![Screenshot_20220515-132133](https://user-images.githubusercontent.com/679113/168470363-d9de096e-c766-44cb-81b2-930d950c2e0f.png)
![Screenshot_20220515-132140](https://user-images.githubusercontent.com/679113/168470364-2d73e6ec-2aaa-4f31-b33c-73af33574621.png)

**Version Info:**
 - App Version: 0.14.4
 - Android Version: Android 8.1.0
 - Device Model: Palm PVG100

**Additional context**
thank you!!!

**Comment by forrestguice** [comment]
This is an old bug (a result of the way it was originally implemented) - the graph always assumes noon is somewhere near the center, but thats only true when the timezone is aligned with the location. When out of alignment the graph shifts left or right (expected), but then fails to wrap to the other side - in the screenshot the left side of the graph should show the end of the day, the evening twilights and nightfall, but these are missing (they've been shifted out of the image to the right).

The warning message is displayed whenever the timezone is more than 3 hours off from the location (whereas local mean time is perfect alignment). Its a crude comparison but it catches most unintentional mistakes - that warning can be disabled from Settings->User Interface, or temporarily swiped away (will return on relaunch). The next minor version (v0.15.0) will be able to suggest a timezone, but reliably mapping locations to timezones isn't easy (there are local solutions but they weigh a lot).

To bring the graph back into alignment you'll need to reconfigure the timezone. A workaround is to configure to `local mean time` so it will always be centered. That fixes the widget, but its not a good solution for the app (where timezone/location misalignment might be intentional). Also, I see location is using "current (last known)" - that's an extra wrinkle I hadn't considered - getting on a plane results in automatic misalignment.

**Comment by Timo-Fi** [comment]
Does this also affect to the 3x2 rectangular word map? if it does, then what would be the most realistic setting (perhaps LTST, apparent solar time, i.e. the local true solar time)? But, when the location is correct (be it either the current local, or as set to some desired location) then why the sun position widgets would need the time zone information at all (from the user, nor from the system)?  After all, the graphs do not have a time axis per se. Should the graphs always show the actual/true situation of the sun, at the location that is chosen? What ever man made convention (about time zone) can not move the earth from it's track. Likely I've missed something here.

I use this opportunity to explain my experience(s) about 1st time installation of the Suntimes, I've done a clean install well over ten times. In my opinion it is not overly smooth, to the extent that it possibly can rather easily upset a new user.  First one has to understand that it is the current location that needs to be specified. Then one has to find the Location dialog, where the default mode is "User Defined': Phoenix, but it can not be removed by the means provided in that dialog. Next one gets the bright idea to change the mode to 'Current (last known)', but unfortunately it does not help any. Then one may tap the 'update' textlink,  and it usually (as there is no gps fix indoors) just dismisses the Location dialog, which can be mind baffling.  So, is there not, inside the  Android somewhere, some kind of location data available to be used at the time of 1st install, just a coarse location (or network derived location) at this point would help a great deal. There surely is in Android the system time zone data. If these could be used automatically as the default setting for clean install, it would be way better for the 1st time user. My approach to this is to open the 'My Location' app by Mirfatif (from F-Droid), go outdoors, monitor the app until it show that gps fix has been achieved. Then switch back to Suntimes and update the gps location in the Location dialog, and finally go back indoors to continue settings.  I always set the 'GPS recent max age to 'any age' so after it is once got it never vanishes. 

Related: could you please tell what does the 'Passive Location, use the passive location provider exactly mean?  Is it "use **only** the passive service" or "use **also** the passive service"? Btw: The Déjà Vu Location Service (from F-Doid) is very capable and working fine under Android 7 (but is lifeless in Android 11).

Now, after this mile long posting, I try to limit long messages, instead I¨ll dig deeply into learning about the various ways the moon affects to the life on earth.

**Comment by forrestguice** [comment]
> Does this also affect to the 3x2 rectangular word map?

It affects the 3x1 lightmap only. 

> Should the graphs always show the actual/true situation of the sun
It's just the way it was implemented - the calculated rise/set times are drawn as overlapping rectangle, where the center is noon in the configured timezone. Only when the timezone is the same (or close to) local mean time will it be centered. Timezone is just an arbitrary offset, and when visualized this way, it is exactly like "moving the earth from its track".

I'm remembering why the app doesn't just center the graph automatically now - it'd mean calculating all of the times twice (once for the configured timezone, then again in local mean time). Better to just to re-implement it (something I haven't gotten around to).

> I use this opportunity to explain my experience(s) about 1st time installation of the Suntimes

The next version (`v0.15.0` will have a "welcome dialog" that should help in this regard. It will include guided configuration of location and timezone. It will expose the large list of places that are available (but not advertised); try `Settings->Places->Manage Places->Add World Places`. I personally use the app with both 'user defined' location and timezone. I've actually be considering removing the 'current (last known)` mode. 

> what does the 'Passive Location, use the passive location provider exactly mean?

It means "use only the passive provider". The app won't initiate location requests, but it can access those that are already occurring. Otherwise the app queries each of the providers in turn (network, gps, etc) depending on whats available. The passive provider is useful for the scenario you described - having a separate app manage location requests. You'll still need to trigger a location update from within the app (its not automatic, passive or otherwise).

**Comment by Timo-Fi** [comment]
Oh, when I found the Suntimes, I soon created several my favorite locations/places ... by looking up their lat/lon pairs on PC from Google maps, copy pasted them into MS Excel sheet for conversion into decimal degrees, then took that sheet into Android, and finally copy pasted the pairs into Suntimes. Then, I found and did the `Settings->Places->Manage Places->Add World Places` and, I must say, I was a little shocked to have so many places, and some had the same title that I had created, but different data.  Then I found my  own places at the end of the list, with some having the same title as in the list.  My immediate thought was "do not do that again". But now I see it is OK. However, I'd rather have it so that I could pick places one by one, as needed.

> I've actually been considering removing the 'current (last known)` mode.

I'm hoping that there could be some way, as an option, to get the 'current' lat/lot so that custom places can be created in situ. Also if possible, indication about the lat/lon source would add "coherence" to the places database. As it can be added manually, from GPS, from network, or from a passive provider.  Perhaps the indication could even be the announced accuracy (in meters or yards), and if manually entered then "unknown" unless user provides it.

Thank you very much for your detailed answers. My problem has been my strong presupposition(s), that so often are true, namely that Android apps are quite simple, their settings are very scarce, and their widgets usually are not that useful. None of that holds with Suntimes! I'm ultra happy with Suntimes, I have one homescreen full of just Suntimes widgets, and 21 notifications that says (out loud via the Volume notify app):

"it is x hour(s) before/after the solar noon".  (where x == 1 to 8, in words)
"the high hours starts/ends, one hour thirty minutes before/after the solar noon".
"the hot hous starts/ends, thirty minutes before/after the solar noon".
"it is now the solar noon".

Even some strangers have approached me asking what was that. BTW, one Googlepoop is haunting, Google allows only some 16 to 21 notifications from one app, in case those notifications are not cleared, then any more do not pass through.
