### ISSUE TITLE
Despite setting units to metric the altitude is displayed in feet

### ISSUE THREAD

**Issue by Knusper** [forrestguice/SuntimesWidget#604]
**To Reproduce**

Go to Settings - Units of Length - Metric

**Expected behavior**

All units are in metric.

**Actual behavior**

The elevation is displayed in feet.

**Version Info:**
 - App Version: 0.14.4
 - Android Version: 11 go
 - Device Model: Motorola e20

**Comment by Timo-Fi** [comment]
On Xiaomi Readmi Note 9T, Android 11 (MIUI 12.5) this change of unit is reflected properly in "Object Shadow" -item in Settings, in "Manage Places" -items, and on the app pages where ever the topographic elevation is displayed.

**Comment by Knusper** [comment]
@Timo-Fi in all those places I see feet - maybe a Android Go problem? ... let's see if the [7cb3e69](https://github.com/forrestguice/SuntimesWidget/commit/7cb3e6929b01278f3174a0d1ed63fe7e92770f25)  solves it.. thanks  so much  @forrestguice for looking into this..  I also found another problem on this device - will report tommorow

**Comment by forrestguice** [comment]
I'm unable to reproduce it either, but I do think its an Android Go problem. I suspect its because there are differences in the activity lifecycle, which causes a 'change listener' to fail to run.

I don't think the setting is actually saved (despite retaining checked/unchecked), and it uses the default every time. That default is locale dependent - its probably possible to force it to display metric by forcing the locale (to something other than en_US).

Anyhow, I'm optimistic the last commit fixed it. Unfortunately there are no Go images for the emulator, or I'd test it directly.

**Comment by Knusper** [comment]
I just tested this, and it works. However, I had to cycle the setting, which was already metric on my system, back to imperial and then to metric to make the UI display metric.
