### ISSUE TITLE
Mute action

### ISSUE THREAD

**Issue by islam2hamy** [forrestguice/SuntimesWidget#617]
Hi @forrestguice ,

How can i add an action to mute/unmute phone ?

Thank you

**Comment by forrestguice** [comment]
I'm not sure its possible, since I don't know of any system [Intent](https://developer.android.com/reference/android/content/Intent) available to directly modify volume settings. 

It is possible to open the volume panel by defining "Action" as `android.settings.SOUND_SETTINGS` (probably not useful).
I think it could be done via a third-party app (that changes volume/do-not-disturb using other api), but I don't know of any. That app would need to accept some `Intent` that Suntimes could trigger.

**Comment by islam2hamy** [comment]
Ok ,
Thank you

**Comment by islam2hamy** [comment]
1- install this app
https://f-droid.org/en/packages/com.roozen.SoundManagerv2/

2- create new action to open this app and call class
com.roozen.SoundManagerv2.MuteActivity
