### ISSUE TITLE
Does not adjust for daylight savings

### ISSUE THREAD

**Issue by nobodyspecial** [forrestguice/SuntimesWidget#62]
The app calculates the sunrises/sunsets using the standard time of the selected time zone. If the time zone is in daylight savings time (CST vs CDT) the rise/set times are 1 hour off.

Currently using version 0.2.1 via FDroid

**Comment by forrestguice** [comment]
Hey can you show me a screenshot of this in action? I'm testing it now against chicago (41.8336, -87.8722) using "user defined" timezone set to "US/Central". It tells me the rise and set times are at 6:45am and 6:39pm, https://www.timeanddate.com/sun/usa/chicago concurs

.. so since I can't reproduce it, I'm hoping to see something unusual in the screenshot that will help explain it and get to the bottom of this.

**Comment by nobodyspecial** [comment]
You can close this I think. My location was chosen wrong.

**Comment by forrestguice** [comment]
I see the problem! A picture really does speak a thousand words. Check your location - that lat/lon is my physical location (the default) in prescott az. That is the sunrise/sunset times where I am, expressed in central time (w/ DST applied).

**Comment by forrestguice** [comment]
I also see the label is chicago, but the lat/lon isn't. I am now thinking there might be some other issue here, which resulted in the default location getting set (instead of actual lat/lon for chicago). How did you set the location? using the gps button?

 a screenshot of the location config dialog might be helpful. the last time the default lat/lon was getting (erroneously) set it was due to a decimal formatting bug. It wouldn't surprise me if something similarly weird was going on.

**Comment by forrestguice** [comment]
oh sorry. I completely missed that sentence under your screenshot. please disregard

**Comment by forrestguice** [comment]
So there isn't any mapping between timezone and location (which imho would be really useful), so when you set the timezone it doesn't affect the location at all, and vise versa. I guess the confusion is you were expecting the location to be changed with the timezone. Incidentally, I think automatically setting timezone to match the location would be a useful feature (but have run into some challenges implementing it).

**Comment by forrestguice** [comment]
anyhow, thank you for reporting. I'm glad dst is working but problems can be subtle - please don't hesitate to open another issue if you discover something else.
