### ISSUE TITLE
Size of sun in 2x1 and 3x1 lightmap widget

### ISSUE THREAD

**Issue by onlycparra** [forrestguice/SuntimesWidget#624]
The size of the sun is too small, which makes it difficult to see (the low color contrast doesn't help). I attach a screenshot. I think the upper two instances have a too tiny sun.
 
![Screenshot_20220921-110155_One UI Home](https://user-images.githubusercontent.com/5915008/191578224-133e25fd-4bc5-47e1-a9ca-fc892169fd7f.jpg)

Thanks.

**Comment by forrestguice** [comment]
Yeah, that is difficult to see. 
If I remember, the circle is scaled to a 'half hour wide', so the reduced width is directly to blame. I guess the fix is to constrain it to some minimum size, or maybe a constraint on height (maybe no less than 1/4 the height).

By the way, those colors can be changed by applying a theme. From the widget configuration tap 'Theme' (next to the selector). I think contrast is fine at the larger sizes (but I'm open to revising default colors too).

**Comment by onlycparra** [comment]
Thanks for the quick answer.
The function of the widget (to me) is to have a quick perception of the 
remaining day. So a big (even huge) sun is great.

Let ph, pw be the widget's  height and width in pixels (or the 
corresponding units). And diam the sun's diameter:

```
diam = ...
ms = min(ph, pw)
if not (diam >= ms/4 && diam <= 3*ms/4):
    diam = ms/2
```

I think that is a complete constraining that should deal with exotic 
homescreens and corner cases.

Claudio


PS: I like the coloring.
PS2: I am thinking now that a vertical lightmap would be cool...

----------------------------------------

Sep 21, 2022 12:05:39 Forrest Guice ***@***.***>:

**Comment by onlycparra** [comment]
Thanks for the quick answer.
The function of the widget (to me) is to have a quick perception of the 
remaining day. So a big (even huge) sun is great.

Let ph, pw be the widget's  height and width in pixels (or the 
corresponding units). And diam the sun's diameter:

```
diam = ...
ms = min(ph, pw)
if not (diam >= ms/4 && diam <= 3*ms/4):
    diam = ms/2
```

I think that is a complete constraining that should deal with exotic 
homescreens and corner cases.

Claudio


PS: I like the coloring.
PS2: I am thinking now that a vertical lightmap would be cool...
