### ISSUE TITLE
dismiss alarm fails to remove alarm notification

### ISSUE THREAD

**Issue by islam2hamy** [forrestguice/SuntimesWidget#665]
**Describe the bug**
Dismiss alarm from notification, didn't remove the notification

**To Reproduce**
1. Set alarm after 5m with every day repeat
2. Just keep your phone unlocked waiting for the alarm
3. Dismiss alarm from notification after it started
4. Alarm notification will not removed

**Expected behavior**
Notification removed after dismiss

**Screenshots**
If applicable, add screenshots to help explain the problem.

**Version Info:**
 - App Version:  0.14.11
 - Android Version: 7.1
 - Device Model: readmi 4x

**Additional context**
Reminder within is set to never

**Comment by forrestguice** [comment]
Thank you. I've been able to reproduce it on my devices.

It seems its only when the reminder is disabled and the alarm is set repeating. I tried disabling repeating and also setting the reminder within to some value, and both are working as expected.

It should be fixed in `v0.14.12`. In the meantime I guess set the "reminder within" to an hour.
