### ISSUE TITLE
New permissions?

### ISSUE THREAD

**Issue by 9662** [forrestguice/SuntimesWidget#67]
An upgrade from 0.2.1 → 0.2.2 asks for these new permissions:
* Modify or delete the contents of your SD card
* Test access to protected storage

I could not find either in the changelog or the code what they might be used for. Would it be possible to clarify? Cheers :smiley:

**Comment by forrestguice** [comment]
there isn't a corresponding issue but its related to this line in the release notes; "app crash on ExportPlaces (api18)." The `Settings->Places->Export` functionality needs this to write the database to file (but only for devices running api 18 or lower).

here's the line that was added to the manifest
`<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" android:maxSdkVersion="18" />`

the code that relies on it is in `getfix.ExportPlacesTask.java`

For api 19 and later its not needed, since the OS allows each app to write to its own space on the sdcard without permissions, but for api18 and lower it results in a crash.

**Comment by forrestguice** [comment]
btw I appreciate your concern over permissions. My goal is to keep their use to an absolute minimum - the app will never require network permissions (or other **** that causes one to doubt what the app is doing). 

I was even reluctant to add the sdcard permissions (what does a glorified clock need w/ the sdcard anyway?!) but it was broken without them.

**Comment by forrestguice** [comment]
ok, I changed that line in the release notes to "app crash on ExportPlaces (api18) (adds permission EXTERNAL_STORAGE) (#67)." ... I will try to be a bit more mindful about documenting this kind of stuff in the future so that changes to permissions at least get their own item in the tracker.

**Comment by 9662** [comment]
Thanks for the clarification. I actually looked at the AndroidManifest.xml file and its history but could not find neither the relevant line nor a recent commit, which made me wonder if the thing hadn't got changed at some other point in the build chain.

I appreciate your concern regarding permissions too! I do think it's fine to use whatever permissions are necessary to provide the desired functionality, and with open source apps, or more generally, those where the source code is available, one can usually check in what way those perms are used, but I guess it doesn't go amiss to have a note in the change logs to avoid unnecessary alarm amongst us paranoid types. :wink: 

And thanks for the app, works a treat! :100:
