### ISSUE TITLE
reschedualed alarms dosnt work

### ISSUE THREAD

**Issue by islam2hamy** [forrestguice/SuntimesWidget#730]
**Describe the bug**
rescheduled alarms doesn't work until app opened manual

**To Reproduce**
1. set a notification
2. Turn off the phone for 1 hour or more
3. Turn on the phone
4. dont open the app before the next notification

**Expected behavior**
The notification will appear
But that doesn't habend

**Screenshots**
![Screenshot_٢٠٢٣-٠٨-٢٢-٢١-٠٥-١١-٩٧٢_com forrestguice suntimeswidget-edit](https://github.com/forrestguice/SuntimesWidget/assets/7989030/a08f5803-27f8-4504-a3f5-2b7d5325f9f3)

**Version Info:**
 - App Version: 0.15.6
 - Android Version: 13
 - Device Model: xiaomi note 12

**Comment by forrestguice** [comment]
Sorry for such a late reply @islam2hamy. 
I'm very busy lately. At least for now, I'm unable to spend much time, or take on new projects.

Regarding this bug.. I think `BOOT_COMPLETED` failed to run because the Xiomi "Autostart" setting is toggled off for some reason. It defaults to disabled. It also wouldn't surprise me if the OS periodically resets it too 🤷 It should be possible for the app to detect when its disabled - the latest version (v0.15.7) displays a warning message.

**Comment by islam2hamy** [comment]
> Sorry for such a late reply @islam2hamy. I'm very busy lately. At least for now, I'm unable to spend much time, or take on new projects.

@forrestguice  , no problem  :)

> 
> Regarding this bug.. I think `BOOT_COMPLETED` failed to run because the Xiomi "Autostart" setting is toggled off for some reason. It defaults to disabled. It also wouldn't surprise me if the OS periodically resets it too 🤷 It should be possible for the app to detect when its disabled - the latest version (v0.15.7) displays a warning message.

Ok , i will take a look for "Autostart"
