### ISSUE TITLE
Confusing "Last Location" and timezone

### ISSUE THREAD

**Issue by sjvudp** [forrestguice/SuntimesWidget#733]
**Describe the bug**
I mainly use the app when traveling to find the local sun times. Since last use abroad there were two Android system updates (all within Android 13), and after having returned back home I realized that the times displayed are significantly wrong, i.e.: useless.

For example when I'm in south of Germany when current sunset is roughly at 6:30 PM I saw:
![Screenshot_2023-10-08-17-52-06-24_178aa8d0014df6d1835fd93b98f98e87](https://github.com/forrestguice/SuntimesWidget/assets/6734808/00e93c64-02b5-4582-afa5-887f46d103e5)

While the mode for "timezone" was set to "System", it was not the current timezone (which was Europe/Berlin, obviously).
Also the "_Last_ location" (Letzter Standort) is questionable: What does "last" refer to? It seems the app stores it's own "last location", but does not update it. In the meantime I had visited different places, and actually that "last" location was several months old.

I had to fix the timezone manually, even though the setting was "System" and the Android system had the correct timezone.

For the location: I think I had set the location to "user-defined" when "current location" did not work (even though GNSS location services *did* work in other applications.

Other applications do not have such problems:
![Screenshot_2023-10-08-17-57-40-87_cc4d16a25272ef628855d41a461682d4](https://github.com/forrestguice/SuntimesWidget/assets/6734808/0e9588aa-597c-4cb6-9155-169ec17d6af3)

![Screenshot_2023-10-08-17-59-10-09_282d022627b3c6a616b39ea68b467221](https://github.com/forrestguice/SuntimesWidget/assets/6734808/35678842-db40-4e91-8976-3e60559e3345)

**To Reproduce**
1. Go to a remote location
2. Try to get the local sun times; if necessary manually pick the location if the location cannot be determined from GNSS
3. Go to a different location
4. Check the sun times

**Expected behavior**
It should be possible to set the current location from GNSS if other applications can. The current timezone should be derived from the Android system correctly. Maybe "Last location" should be changed to "User-defined location" if the location has a fixed setting (is not "current location").

Maybe be more verbose when the setting is "current location", but the location cannot be determined. Preferably explain why.

**Screenshots**
See above.

**Version Info:**
 - App Version: 0.15.7
 - Android Version: 13 (ColorOS 13.1)
 - Device Model: Oppo Find X5 Lite

**Comment by forrestguice** [comment]
Thanks for the report.
It's a shame this isn't working correctly. It sounds like it was prior to recent updates?

> the "Last location" (Letzter Standort) is questionable: What does "last" refer to? It seems the app stores it's own "last location", but does not update it. In the meantime I had visited different places, and actually that "last" location was several months old.

That "last known" label comes from android developer [docs](https://developer.android.com/training/location/retrieve-current); maybe there is a better label for the German translation. All translations are user contributions, so I'm very appreciative of any effort to improve them.

In this context it is the "last known" location the app knows about. The app must periodically request location updates, which is supposed to occur whenever the app is launched or resumed, but also happens when clicking the location pin (first icon on the toolbar when "current location" is selected). It sounds like either the app is failing to make these requests, or the system is failing to provide them. The "recent max age" setting (in `Settings -> Places`) also comes into play to avoid making active requests (turning GPS on, etc) if the system is already keeping its own "last known" location.

I'm curious, does clicking the pin update to the actual current location? or querying GPS when using "user defined"?

I don't personally use "current location" and have even considered outright removing it for its trouble, so it doesn't surprise me there is an unnoticed bug. I typically use "user defined" location and periodically add locations whenever I travel (changing the label, then using the gps/location button to query GPS). This mode of operation should be more reliable (better tested at least).

As for time zone I leave it set to "System". There appears to be a separate confounding bug highlighted in your first screenshot. I believe this is a UI bug isolated to the time zone dialog; only the selector (bottom red circle) is incorrect. The rest of the UI indicates the system time zone (Europe/Berlin) is being used (with twilight times consistent for some location in the Atlantic).

**Comment by forrestguice** [comment]
I'm looking at that screen shot again.
The app is actually configured to "user defined" and not "current location" as I assumed (I don't see the update location icon). I think the "last known" label is an artifact from being previously configured to "current location" (possible source of confusion). If the mode were switched at some point to "user defined" (and then forgotten) it might explain why that value fails to update.

**Comment by sjvudp** [comment]
Sorry, for not responding earlier. Here is some extra information:
When I try to set the location to the current location, by enabling "GPS", then selecting "Aktueller Standort" (current location), **nothing happens**. Specifically I don't thee the indicator that the current position is being queried (Android displays an icon in the status line if so). What I did not realize before is that I'll have to tap on the crosshair icon to retrieve the current position (I thought it's a status indicator only). After having tapped it, the position was updated immediately.
So the reason for having set the location manually was that I did not manage to get the current position be set automatically.

**Comment by forrestguice** [comment]
Thank you, I'm glad to hear that the GPS functionality itself is working. 👍 

Some updates..
I've fixed the bug in the time zone selector. I've also changed the labels when switching away from "current location" to help avoid confusing the two modes (otherwise the "crosshairs" icon is the only indicator). The app should now automatically request the location when its launched/resumed (I discovered reasons why this wasn't happening). It should also display a warning if Location permissions are revoked - this wasn't applicable in your case, but I discovered that if permission is rejected more than twice, Android will refuse to display the dialog a third time (failing without any indication).

These changes will be published in `v0.15.8`, which should be on F-Droid in ~2 weeks (probably another week before I tag the release, and a week to allow F-Droid to detect and build it).
