### ISSUE TITLE
Release build apk

### ISSUE THREAD

**Issue by foxjaw** [forrestguice/SuntimesWidget#742]
F-Droid version is okay. But also can you post apk builds in releases ? I'm actually tracking your repo through [Obtainium](https://github.com/ImranR98/Obtainium). It tracks updates directly from source releases. GitHub is also 10 fold faster than F-Droid repos.

**Comment by forrestguice** [comment]
Its definitely worth considering, however the situation itself is kind of complicated. 

F-Droid currently builds, signs, and publishes the main app (and calendar add-on). These aren't published elsewhere so this turns out to be extremely convenient for me. I need only tag new releases and F-Droid will automatically build them (typically a week later). 

To publish my own binaries (here on GitHub, or to Google Play), it becomes necessary to build and sign the apk myself. We could then have F-Droid use that apk instead (reproducible builds) - a lot of apps are doing this recently. However, because the signature will change, it means existing users will be forced to uninstall and reinstall (no upgrade path). So unfortunately, its not the sort of change I can make casually. It will have to be very deliberate.

Meanwhile the other add-ons are all self-published (good candidates for Obtainium). I actually wouldn't mind if F-Droid published these these too. If someone wants to make a [rfp](https://gitlab.com/fdroid/rfp)), I'm fine with that. That might be a good opportunity to test out reproducible builds before doing it with the main app.











I currently

**Comment by forrestguice** [comment]
> GitHub downloads way faster than F-Droid.

Ahh, I understand now. I've uploaded the apk built by F-Droid to releases. (v0.15.10) 
I'll try to make a point of doing whenever I verify the app has been built.

I'm considering creating a "Suntimes F-Droid repo" (hosted here via GitHub pages).
That seems like another way to offer a quicker download, and would help advertise available add-ons.

**Comment by forrestguice** [comment]
I've going to stop uploading to Github releases. I gave this a try, but recently received a report where it was a source of confusion (#771).

Instead, I've published the Suntimes related apks to their own F-Droid repository. There's more info about that in #772.
The download should be as fast as Github releases (since the hosting is the same).
