### ISSUE TITLE
Doubt about some untranslated strings

### ISSUE THREAD

**Issue by naoliv** [forrestguice/SuntimesWidget#747]
Hi!

I was taking a look at Widgets section of Suntimes (version is `0.15.8 (2264f789d)`) and, after clicking on the puzzle icon, I can see that, in pt_BR, there are some untranslated strings.
For example, these last 3 strings:

![](https://github.com/forrestguice/SuntimesWidget/assets/982338/7eb17b67-f187-4d24-b399-2115e53678cd)

I guess that the "Update All Widgets" should be https://github.com/forrestguice/SuntimesWidget/blob/971bc102f8c8f355f7467e8cac8398c22716a4f4/app/src/main/res/values-pt-rBR/strings.xml#L516 right?

I don't know if this issue was fixed on a later commit, somehow the XML/values are wrong on these lines (or maybe the strings are missing) or something else.

Any light on this, please?
Thanks!

**Comment by naoliv** [comment]
Also on Themes:
![](https://github.com/forrestguice/SuntimesWidget/assets/982338/2f65141c-0ce3-4ea9-a548-628657744c5f)

I don't see anything with "translucent" at SuntimesWidget/app/src/main/res/values-pt-rBR/strings.xml
Maybe these strings aren't set as translatable?

**Comment by forrestguice** [comment]
> I don't know if this issue was fixed on a later commit, somehow the XML/values are wrong on these lines (or maybe the strings are missing) or something else.

I think doing a `Clear All` from the Actions screen will fix this.
Its a side-effect of the way its implemented (storing the actions in sharedprefs); your current list was initialized before those strings were translated.

> I don't see anything with "translucent" at SuntimesWidget/app/src/main/res/values-pt-rBR/strings.xml
Maybe these strings aren't set as translatable?

Unfortunately the widget theme names are still hard-coded. I remember having some difficulty making these translatable (years ago). I'll take another look though. I've been able to solve some translation challenges since then. I'd just forgotten about these.
