### ISSUE TITLE
Visual interface partly clipped, no scrolling

### ISSUE THREAD

**Issue by tymcat** [forrestguice/SuntimesWidget#754]
**Describe the bug**
Types and numbers close to the border are clipped, the lowest sentence is unreadable (but can be clicked). 

Could be caused my my smaller than extra large screen: Samsung Xcover Pro 5.
![Screenshot_20231226_172025_Suntimes](https://github.com/forrestguice/SuntimesWidget/assets/5269105/6d6f0337-1327-4541-8a22-78c6bab45fc0)
![Screenshot_20231226_171933_Suntimes](https://github.com/forrestguice/SuntimesWidget/assets/5269105/815612d1-752e-486b-ae3d-c4cb8384db3e)

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain the problem.

**Version Info:**
 - App Version: [e.g. 0.14.3]
 - Android Version: [e.g. 10]
 - Device Model: [e.g. Pixel 6]

**Additional context**
Add any other information about the problem here.

**Comment by forrestguice** [comment]
Thanks for the report.

It looks like the app is using "Large" text-size. A workaround would be to reduce that setting to "Normal". 
I can understand how that would be undesirable though. I'm optimistic the clipping in the first screenshot can be eventually fixed.

A workaround to the problem in the second screenshot is to change the "Show Header Labels" setting to either "none" or "azimuth". The issue here is the longer strings in the translation (combined with Large text).

**Comment by tymcat** [comment]
It was set to "normal". I changed it to small, but that makes the text really tiny. Still readable though.
