### ISSUE TITLE
[Feature request] Backup Option for App-Settings ...

### ISSUE THREAD

**Issue by volker001** [forrestguice/SuntimesWidget#757]
Is it possible to save the settings in an individual path, (including the set up widgets)?
It would be a shame if everything had to be reset again, after a crash or device change.

**Comment by forrestguice** [comment]
It's a difficult situation. I think saving/restoring app settings is straightforward, but doing the same with widgets presents a serious challenge. The problem is the app isn't capable of creating widgets itself (this is done by the launcher), so there is no direct way to go about restoring them later.

There might be a roundabout solution though...
I think some launchers (nova) are able to backup their widgets too, but it only includes things like size and placement. It works for extremely simple widgets. The Suntimes widgets would still be missing their individual configurations afterward. This is something the app needs to backup/restore on its own, however since the widget ids will have been changed, it also needs to guess which widget is which 🤷‍♂️.

**Comment by volker001** [comment]
Thank you,
Export / Backup the App-Settings:
I don't see any Export/Backup Options in the app's settings. 
Did I miss it?

**Comment by forrestguice** [comment]
> Did I miss it?

Sorry for the misunderstanding. What I meant was that implementing such a feature for the app settings will be straightforward. The feature is still missing (but likely to be added sometime soon). 

Also, IIRC, the built-in Android backup should work too, but only to a limited degree. A large number of settings used by the app are technically "widget settings", and so are currently omitted from backups. They aren't included because a handful of those settings (location related mainly) are considered sensitive data that I'd like to prevent ending up on some cloud.
