### ISSUE TITLE
custom date format is not saved

### ISSUE THREAD

**Issue by milkcreeks** [forrestguice/SuntimesWidget#759]
**Describe the bug**
A clear and concise description of what the bug is: When using Date format ^custom in changing to Rolex Oyster Perpetual  (Wed, Jan 1) "EE, MMM d" does not stay set and reverts to default.

**To Reproduce**
1. Go to settings , widgets, date widget, date format dropdown , Custom
2. Input custom date format  "EE, MMM d" checkmark save
3. See date format on widget has not change to Rolex Oyster Perpetual 
4. open settings again to see "EE, MMM d" not set

**Expected behavior**
A clear and concise description of what you expected to happenin:Expect to see a widget with a date format such as "Wed, Jan 1"

**Screenshots**
If applicable, add screenshots to help explain the problem: Upon request.

**Version Info:**
 - App Version: 0.15.9
 - Android Version:  10
 - Device Model: Pixel variant

**Additional context**
Add any other information about the problem here.

**Comment by forrestguice** [comment]
Thanks for taking time to report.
I think I've figured out why this isn't working. It should be fixed in `v0.15.10`.

In the meantime, I think you can "force it" to work by clicking enter/accept on the onscreen keyboard first (and then afterward clicking save at the top). 

The underlying problem is that custom format isn't applied until the textview loses focus, so clicking save while it still has focus effectively discards the changes.

**Comment by forrestguice** [comment]
Thank you, and yeah, this app is a personal project for many years now.

> Do you happen to know the key mapper code for "RETURN"?

Sorry, I don't know. I mentioned the keyboard because it seemed like the quickest way to lose focus, but maybe its a contributing factor too.

> I also noticed you changed my reporting a bug title.

I think how you reported it was fine. The bug occurs when entering any custom date format though, so I changed it to what will be noted in the changelog.

btw, I wasn't previous familiar with this format. We can add it to the list of defaults if you think its something others might want too.
