### ISSUE TITLE
Can't interact with app after install. Flashes/strobes (seizure warning)

### ISSUE THREAD

**Issue by Phoenix616** [forrestguice/SuntimesWidget#760]
**Describe the bug**
After installing the app and opening it one can't interact with it and it flashes/strobes between the screen where you press "next" and some font option/welcome screen. (Also switching to another app is difficult from the app switcher. (See video))

**To Reproduce**
1. Install app (from F-Droid)
2. Open it
3. Have observe described behaviour

**Expected behavior**
For the app to work and not have some seizure-inducing strobeing effect...

**Screenshots**

<details>
<summary>Video from the effect (seizure warning!)</summary>

https://github.com/forrestguice/SuntimesWidget/assets/5768781/127ece36-be78-4b7b-b308-9a45dece5fac

</details>

**Version Info:**
 - App Version: 0.15.9
 - Android Version: 13 (LineageOS 20-20231021-NIGHTLY-beyond0lte)
 - Device Model: Samsung Galaxy S10e (beyond0lte)

**Additional context**
Looks like it's re-opening the app again and again to me

**Comment by forrestguice** [comment]
Thanks for the report. 
Is it doing this with the previous version `v0.15.8`?

There were recent changes in the welcome activity, so I'm thinking this behavior is something I might have introduced then.

**Comment by Phoenix616** [comment]
0.15.8 seems to not have the issue.

**Comment by forrestguice** [comment]
Thank you again for reporting this. It should be fixed in `v0.15.10`.
To test it, either navigate `Settings` -> General -> Welcome Screen", or reset/clear app storage.

I couldn't reproduce the bug on my devices for some reason, but the problem is apparent. The activity is recreated whenever the selected theme is changed; the flashing observed is the activity finishing/starting over and over (infinite loop).

The bug was introduced after refactoring the "theme buttons" to a spinner. For some reason the spinner's onValueChanged listener is being fired when initialized. Maybe some internal behavior is recently changed, or some accessibility related option is responsible :shrug:, but I thought I was already taking necessary precautions. The fixed listener now tracks its initial position (to avoid firing unnecessarily).
