### ISSUE TITLE
widget doesn't update

### ISSUE THREAD

**Issue by cessna151** [forrestguice/SuntimesWidget#77]
The widget doesn't update the sunrise/sunset times each day without running the app itself.
:large_orange_diamond:

**Comment by forrestguice** [comment]
weird. what's your OS version? I'll try to test for it, but haven't noticed this before.

the widget update interval is set in https://github.com/forrestguice/SuntimesWidget/blob/master/app/src/main/res/xml/suntimeswidget_info_0.xml - its set to 24 hrs. 

..my thinking is it might actually be updating, just not as expected - if I add a widget at 11PM its not going to update again for another 24 hrs (until the interval is hit, or the OS decides to reload widgets) - that's 23 some hrs of displaying the wrong time.

try this. add a widget, then wait 25 hrs (w/out opening the app). does the widget still display yesterday's times? if so we've got a real problem :\ I'm hoping its the scenario described above, in which case best I can do is lower the interval (to maybe 4hrs).

**Comment by cessna151** [comment]
I'm on Android 5.1.1
The current widget has been on my home screen for 3 days now without any change (i have not launched the app for 3 days). I will go ahead and remove it and start a new one just to be sure.
:large_orange_diamond:

**Comment by cessna151** [comment]
Old widget removed, new one added. I'll get back to ya in a couple days. Screenshots attached just in case it helps...

![11](https://cloud.githubusercontent.com/assets/15715378/22620832/2be7242c-eae2-11e6-9dff-195c0c95ac04.png)![22](https://cloud.githubusercontent.com/assets/15715378/22620834/2e816116-eae2-11e6-8450-c551f81d9775.png)![33](https://cloud.githubusercontent.com/assets/15715378/22620835/30163f2e-eae2-11e6-8686-300bcc435669.png)

**Comment by cessna151** [comment]
Still not updating :(  Also, i don't know if this is related or a separate issue but tapping the widget does not bring up the reconfigure screen unless the app is already running in the background.
:large_orange_diamond:

**Comment by forrestguice** [comment]
dang. I can't seem to reproduce it on my device (running 4.4.4). The problem w/ the reconfigure screen is probably not directly related, but who knows, wouldn't surprise me if it was another symptom of the actual root cause.

anyhow, thanks for the report - I'll look into the cause of both issues, and will keep this issue open (indefinitely) until I figure out whats going on.

**Comment by forrestguice** [comment]
I guess there is something else we might try - open fdroid and force a downgrade to the earliest version they still have archived. Then test again. If it works then I know I introduced the bug somewhere along the way. I'm betting its probably been there along though.

**Comment by cessna151** [comment]
I've discovered the source of the problem. In my phone settings there is a place to select restricted apps which prevents them from performing background tasks. Apparently my phone restricts all new apps by default. Unrestricting this app allows it to update as it should and also taping the widget now opens the configure screen as it should. 

This has uncovered another issue and i figure i'll just post it here. If this should be a separate issue, my bad. Now when the widget updates, the appearance of the widget changes as you can see in the following screenshot.

I also have a simple suggestion. Could the widget update at midnight instead of 24 hours after it was created? This would prevent showing incorrect times.

![screenshot_2017-02-08-13-30-27](https://cloud.githubusercontent.com/assets/15715378/22752458/992a5618-ee06-11e6-883e-ee986cc71bf7.png)
:large_orange_diamond:

**Comment by forrestguice** [comment]
cool, I'm glad we figured out at least one problem.

You should be able to click on the widget until resize handles appear, then resize the widget horizontally - the screenshot shows the widget resized (looks like 1x3). Is it resizing itself on update? (because that shouldn't happen)

I've been looking into fixing the update behavior. I think this can be done no problem - http://stackoverflow.com/questions/5534470/update-widget-on-day-change. Its on an interval now because that was the simplest way (and I'm a bit lazy), but fixing this w/ AlarmManager doesn't look too bad.

**Comment by forrestguice** [comment]
ok, this sounds similar to another problem I've noticed (on some devices) where the widget refuses to resize at all - I traced the cause of that to an edge case involving screen sizes / pixel density (but its still unresolved).

What size is your screen? and the pixel density? This app should tell you if you don't know offhand: https://f-droid.org/repository/browse/?fdfilter=density&fdid=com.jotabout.screeninfo 
I've also been able to find useful info about a specific device's screen at phonearena.

With some luck I'll be able to reproduce this with the emulator.

**Comment by cessna151** [comment]
![screenshot_2017-02-12-18-24-02](https://cloud.githubusercontent.com/assets/15715378/22867244/7ef22498-f152-11e6-9c11-1912d3931766.png)
:large_orange_diamond:

**Comment by forrestguice** [comment]
thanks. I think I've been able to reproduce it (and fix it). 
my observations..

1) in the first screenshot the widget is neatly centered. also the screen is 4 cells wide. I think that suggests the widget was resized at some point - even though its displaying the 1x1 layout, it actually must be 1x2 (or maybe larger) for it to be centered like that (if it was really 1x1 it would be in alignment with the app icons below it).

2) after reconfiguring the layout changes to 1x1 every time (this is the bug) - I'm able to reproduce your first screenshot by resizing a widget to 1x2, then reconfiguring - now its (incorrectly) displaying the 1x1 layout neatly centered.. Then I wait for the update interval (which I lowered to a couple min for testing) - the widget suddenly changes to the 1x2 layout (reproducing your second screenshot - its centered over the two center cells).

I think its the situation you described but from a different perspective - the initial screenshot is showing the bug, the widget then auto updates and corrects it, and then reconfiguring causes it to happen again. I went looking for it in the code and sure enough the reconfigure button was forcing the 1x1 layout.

So what I'm unsure about is if your widget was actually resized (or maybe moved around) at some point, or if it started off that way (taking up 2 cells in the center of the screen with the 1x1 layout)? that would be another problem. When I initially add a widget its always 1x1 (but within a space of 1x1).

Anyhow, I actually like the appearance in your first screenshot - I've added a new option to make it intentional - 1x1 widget centered within whatever space is available.

**Comment by cessna151** [comment]
Yes, what you describe sounds accurate. This is fantastic news! Thanks so much! Just out of curiosity, how long does it take for an update like this to be available from f-droid?
:large_orange_diamond:

**Comment by forrestguice** [comment]
I need to add a tag, then fdroid should detect that within a day or so, try to build it, and then available in the repo within another day or so.

I usually let at least 4 weeks go by between tagging stuff, and let the commits pile up. Its going on several months now - definitely time to cut a release - I'll try to get it tagged in the next week.

**Comment by forrestguice** [comment]
tagged. it should be on fdroid within a day or two. 
thanks for reporting these issues. I appreciate it - I wouldn't know something was wrong otherwise. the widgets should now update at midnight (inexact; give or take a few minutes),

please don't hesitate to open one if you discover something else (or if this one still seems to be a problem).
