### ISSUE TITLE
View Date limited to 1000 days in the past

### ISSUE THREAD

**Issue by kshpytsya** [forrestguice/SuntimesWidget#770]
Attempts to "View Date" more than 1000 days in the past or in the future are silently ignored.

**To Reproduce**
1. Click the "..." menu
2. Click "View Date" menu item
3. Pick any date that is three years (3*365=1095) in the future or in the past
4. Click check mark to confirm date selection
5. See that the chosen date is silently ignored, leaving previously selected date, and a confused user.

**Expected behavior**
It should be possible to view arbitrary date not limited to -1000..+1000 days from today. If this is really impossible for some valid reason, the date selector should indicate that with some explanation, and make it impossible to select an unsupported date. Also, if already displaying non-current date on the main screen, date selector should start with that date selected, and not today's date.

**Version Info:**
 - App Version: 0.15.11 (4969294e8)
 - Android Version: 14; 9.0
 - Device Model: Pixel 8 Pro; Galaxy S10e

**Comment by forrestguice** [comment]
Thanks for the feedback. I appreciate it.
Issues with the date selector will be fixed in the next patch version.

I'm curious about your use case, if you can share more details. 
_How many years into the past/future are you interested, and for what purpose?_

The current +-1000 days limitation is arbitrary, but even with technical limitations on the date range, it should be possible to allow selection of +- hundreds of years. e.g. the underlying library, Time4J, allows for dates up to year 3000, but I'm a bit dubious of the accuracy/result.

**Comment by kshpytsya** [comment]
My specific use case which led me to this discovery was trying to go back to the year of my birth (1979) to determine the date of Chinese New Year, which is the second new moon after the winter solstice. So, a one-off use case but why not.
