### ISSUE TITLE
Add day length difference from the day before and fix minute symbol

### ISSUE THREAD

**Issue by bugith** [forrestguice/SuntimesWidget#773]
Great App !
The symbol of minute is min, not m (m stands for meter) : p145/147 [The International System of Units (SI)](https://www.bipm.org/documents/20126/41483022/SI-Brochure-9.pdf/fcf090b2-04e6-88cc-1149-c3e029ad8232) 

It would be nice if we had how many min-s we have from the day before, this way:
![Screenshot_20240217-182015](https://github.com/forrestguice/SuntimesWidget/assets/6240207/fd121712-af82-46b1-a75a-7d56258048c0)

**Comment by verdulo** [comment]
I corrected the unit in translations to Polish and Esperanto. Just edit the following string:
https://github.com/forrestguice/SuntimesWidget/blob/f7ce8a6630dca51b94af34f74ac0239341f2623d/app/src/main/res/values-fr/strings.xml#L179

**Comment by bugith** [comment]
"min" is ISO, shouldn't be translated.
Also, I'm not a coder to understand if what I read on line 173 ([link](https://github.com/forrestguice/SuntimesWidget/blob/f7ce8a6630dca51b94af34f74ac0239341f2623d/app/src/main/res/values-fr/strings.xml#L173)) is related to the delta time feature I proposed in this very issue, but I though it is better to show Today minus Yesterday instead of Tomorrow minus Today (or Day minus Day-1).  Just a thought.

**Comment by forrestguice** [comment]
Thanks for taking time to report. 

This feature will be added to the main app soon. I've been meaning to add it for awhile actually, but somehow it keeps slipping my mind. Its already available for widgets (since a very early version).

> I though it is better to show Today minus Yesterday instead of Tomorrow minus Today (or Day minus Day-1).

The widgets have "show comparison" and "compare against" (today/yesterday) options. It will be the same for the app.

> "min" is ISO, shouldn't be translated.

Almost every string in the app is translatable, so as to give translators ultimate control over what appears on the screen. e.g. the Chinese, Russian, and Hungarian translations have replaced these symbols entirely.

I might argue that "m" vs "min" isn't a problem so long as their isn't any ambiguity - both are widely understood. However, the lower left hand corner of your screenshot has"m" in the context of meters, and that same ambiguity appears again in "sun position" dialog. 

So I've gone ahead and changed this from "m" to "min" for in all the translations that default to METRIC.
I've left it unchanged for "American English" (`en_US`)).

**Comment by bugith** [comment]
Thanks to you for extensive answer Forrest. Nice App and great Dev !
