### ISSUE TITLE
[Feature request] Culturally neutral cross quarter day names

### ISSUE THREAD

**Issue by elydpg** [forrestguice/SuntimesWidget#804]
It's nice to see that the cross quarter days are included as part of the solstices and equinoxes events! However, i noticed that the names of the cross quarter days are **Imbolc**, **Beltane**, **Lughnasadh**, and **Samhain**. This is a problem for two reasons:

1. Since those terms are specific to celtic culture, derived from the names of celtic holidays, they are not very recognizable in other cultures. As such, they don't translate well. (Granted, the Gregorian Calendar technically has the same problem but it has become so widespread that it is now universally recognizable, and adding other calendars is no easy task.)
2. The people who do observe these holidays typically don't do so on the actual astronomical day of the midpoint: Imbolc is usually celebrated on Feb 1, Beltane on May 1, Lughnasadh on August 1, and Samhain on November 1 (in the northern hemisphere).

Thus, I propose a different naming scheme for the cross quarter days be used. Probably the simplest way to do it is to use the names of the seasons that the cross quarter days transition:

**Winter/Spring cross quarter** for Imbolc  
**Spring/Summer cross quarter** for Beltane  
**Summer/Fall cross quarter** for Lughnasadh  
**Fall/Winter cross quarter** for Samhain

This specific naming scheme has the added benefit that "cross quarter" no longer needs to be parenthesized, and it is very easy to localize. Curious what others think about this tho; perhaps there are other names that could work?

**Comment by elydpg** [comment]
Update: After doing a search, I found #719 which seems to discuss this exact issue: Using the February cross quarter as an example, it seems that the name **Spring cross quarter** was previously used instead of **Imbolc** but was changed to the celtic name because it is too ambiguous. Guess you can't please everyone 😂

I am aware that some cultures start the (northern hemisphere) spring season on the February cross quarter while others start it on the March equinox, though I feel my proposals are easily understood in both cases (**Winter/Spring cross quarter** can either mean the cross quarter in between winter and spring or the cross quarter ending winter and starting spring)

**Comment by forrestguice** [comment]
> Update: After doing a search, I found https://github.com/forrestguice/SuntimesWidget/issues/719 which seems to discuss this exact issue:

Yep, I was just thinking that development is definitely cyclical - fix something once, then plan on fixing it another dozen times. 😄 

I'm happy to revisit this though. I've noticed other feedback where users prefer to hide these labels. I don't exactly love them either.

```
Winter/Spring cross quarter for Imbolc
Spring/Summer cross quarter for Beltane
Summer/Fall cross quarter for Lughnasadh
Fall/Winter cross quarter for Samhain
```
This seems entirely reasonable, so I will probably make that change in `v0.16.0`.


> looking at some of the translations I see that those strings are currently left untranslated 😢

Some translations definitely get more attention than others. A few get regular updates, but most go a long time without attention. So it might actually be fortunate these lines are still TODO, since this means changing/fixing these lines yet again.

>The people who do observe these holidays typically don't do so on the actual astronomical day of the midpoint: Imbolc is usually celebrated on Feb 1, Beltane on May 1, Lughnasadh on August 1, and Samhain on November 1 (in the northern hemisphere).

As an aside, I remember reading an interesting blog on this topic back when implementing it.
https://www.universetoday.com/119983/crossing-quarters-would-the-real-astronomical-midway-point-please-stand-up/
