### ISSUE TITLE
[Feature request] try-force milestone

### ISSUE THREAD

**Issue by HolyNameSoftware** [forrestguice/SuntimesWidget#814]
I hereby issue a gratification to you for at least trying to make a useful app. I see you have had around 800 bugreports. If it was DOS maybe you wouldn't have had such a hard time wouldn't you agree. That somehow we should be able to get useful data onto the screen.

**Comment by forrestguice** [comment]
Sorry, but I'm having difficulty understanding what you are trying to say.

**Comment by HolyNameSoftware** [comment]
Hint: Think The Legend of Zelda.

**Comment by forrestguice** [comment]
oh, lol.
Yeah, the count is getting up there. The project is going on 7 or 8 years old now, so maybe in another year or two it might break 1000. That number also includes pull requests and other merges. I think the actual issue count is closer to 400. 

> If it was DOS maybe you wouldn't have had such a hard time wouldn't you agree

Sure. The Android ecosystem is "fragmented" and the APIs are always changing. I think developing for it feels like playing Castlevania. Here's the playing field (https://apilevels.com/), which is constantly scrolling, forcing developers to jump from one level to the next until its game over.

**Comment by HolyNameSoftware** [comment]
Heuristically "try-force" is to say: under the oppression of darkness you have to beat the game even to start trying: a little bit of a riff on tri-force. Castlevania yeah 'vampires'. Most of whatever was made was done in Google Summer of Code 2013 which is mostly ports of code from DOS and onwards. I guess the API is supposed to let coders focus on coding and not hardware-software interactions. It is not only API it is also libs like I said about don't just be building on top of libs. 
 Looking at API levels.com why would anybody build for old APIs why should old API be in the "playing field" as you say. Old API should be deprecated or obsolete. I'm trying to envision how to play.

**Comment by HolyNameSoftware** [comment]
Heuristically "try-force" is to say: under the oppression of darkness you have to beat the game even to start trying: a little bit of a riff on tri-force. Castlevania yeah 'vampires'. Most of whatever was made was done in Google Summer of Code 2013 which is mostly ports of code from DOS and onwards. I guess the API is supposed to let coders focus on coding and not hardware-software interactions. It is not only API it is also libs like I said about don't just be building on top of libs. 
 Looking at API levels.com why would anybody build for old APIs why should old API be in the "playing field" as you say. Old API should be deprecated or obsolete. I'm trying to envision how to play. 

Anyway, E for effort on your app.

**Comment by forrestguice** [comment]
I own devices that run these older apis. The code I write is for my own use. Full stop.
I shouldn't have to explain my motivations.

Maybe the question you should ask yourself is why most older devices can't be upgraded, and why the expectation is that you should buy a new device every few years and throw the old one away. I am not for forced obsolescence, and so I'll make a point of supporting the hardware I was foolish enough to buy.

> I guess the API is supposed to let coders focus on coding and not hardware-software interactions.

Is your only development experience on ancient platforms like DOS? The expectation that app developers should be "close to the metal" is absurd, and of course libraries (apis) written for the OS in question serve as layers of abstraction.

> don't just be building on top of libs.

Should I have written my own library?! Suntimes was designed around an interface where each concrete implementation is a wrapper around some library. If you don't like Time4J you are welcome to write your own algorithms that produce the results you are expecting - the application supports that. Of course as the app developer, I'm still required to have domain knowledge - to recognize when the library is producing correct results. If you find problems though, they aren't my problems but problems in the library, and we can fix them for everyone by fixing them there.

> Anyway, E for effort on your app.

Gee thanks. 🙄 You should realize this comment sounds condescending.
I've actually wondered about your tone several times now, but since its clear that English is not your primary language, I concluded that you are probably unaware when people take offense at either what you've said, or how you've said it.

**Comment by HolyNameSoftware** [comment]
FWIW, you are trying. Positive reinforcement is positive even if you feel you deserved more to be offended.

**Comment by HolyNameSoftware** [comment]
> I own devices that run these older apis. The code I write is for my own use. Full stop.
> I shouldn't have to explain my motivations.
> 

White knuckles. No you shouldn't have to explain your motivations because it doesn't have much bearing on producing a finished app 8 years later. Why you started doesn't really make a product finished it's become trivial and I don't recall asking.

> Maybe the question you should ask yourself is why most older devices can't be upgraded, and why the expectation is that you should buy a new device every few years and throw the old one away. I am not for forced obsolescence, and so I'll make a point of supporting the hardware I was foolish enough to buy.
> 

...

> > I guess the API is supposed to let coders focus on coding and not hardware-software interactions.
> 
> Is your only development experience on ancient platforms like DOS? The expectation that app developers should be "close to the metal" is absurd, and of course libraries (apis) written for the OS in question serve as layers of abstraction.
> 

Guess so. The purpose of this app was already accomplished in DOS Astrolog. I previously stated DOS **and onward**.

> > don't just be building on top of libs.
> 
> Should I have written my own library?! Suntimes was designed around an interface where each concrete implementation is a wrapper around some library. If you don't like Time4J you are welcome to write your own algorithms that produce the results you are expecting - the application supports that. Of course as the app developer, I'm still required to have domain knowledge - to recognize when the library is producing correct results. If you find problems though, they aren't my problems but problems in the library, and we can fix them for everyone by fixing them there.
> 

Well, yes, you should have written your own library. Radioactive concrete? Time4J is apparently an entire software encapsulated into Java as a "library". Why are you calling this (full software) "library" an algorithm as if it is a single algorithm which is governing the appearance of the Sun? I aforementioned in another post it seems to me you need a stable point of reference, look up at the Sun - with regards to "domain knowledge". 

> > Anyway, E for effort on your app.
> 
> Gee thanks. 🙄 You should realize this comment sounds condescending.
> I've actually wondered about your tone several times now, but since its clear that English is not your primary language, I concluded that you are probably unaware when people take offense at either what you've said, or how you've said it.
> 

Forget tone, in a mode of communication without audio and video you should pretty much take it for monotone.

> 
>

**Comment by forrestguice** [comment]
So its not my imagination that you are tone deaf? I'm sorry but your mode of communication is rude. I've given you too much of my time already. Please feel free to report bugs - I will fix them - but this back and forth between us is over.
