### ISSUE TITLE
Wrong calculation for the repeated alarm

### ISSUE THREAD

**Issue by islam2hamy** [forrestguice/SuntimesWidget#831]
**Describe the bug**
Wrong calculation for the repeated alarm

**To Reproduce**
1. Set notification alarm , 10m before any event , with repeat every day
2. wait for the notification , and remove it from the notifications
3. open the app to see next repeat

**Expected behavior**
Correct calculation for the next repeated alarm

**Version Info:**
 - App Version: 0.16.1
 - Android Version: 7.1.2
 - Device Model: Redmi 4x

**Comment by forrestguice** [comment]
The rescheduling part should happen when the notification is dismissed. It seems that isn't happening, so when the app is re-opened it still shows the previously scheduled time.

**Does it work correctly if you tap the notification instead of swiping/removing it?**

I've noticed another bug while trying to reproduce this one. The foreground service is still running after the notification is shown. The progress message should only appear for a moment, but it sticks around until the notification is dismissed.

**Comment by islam2hamy** [comment]
> **Does it work correctly if you tap the notification instead of swiping/removing it?**

No

**Comment by forrestguice** [comment]
hrm, it must be a different problem than the one I'd assumed.
I think I'll need to see a before / after screenshot of the alarm list to understand better.

**Comment by islam2hamy** [comment]
Let me test some thing about DST , as my old phone android 7.1.2 doesn't support it with Egypt

**Comment by islam2hamy** [comment]
Ok,
now after change app location time to Etc/GMT-3 , the calculation for the next repeated alarm is correct

But if the phone is restarted , it will make a wrong calculation

**Comment by islam2hamy** [comment]
🤐,
i have found that the "use app location" option in alarm was activated.
very sorry for that.
