### ISSUE TITLE
[Bug] - Begin of a major moon phase in the moon dialog shows two different times, depending on the row

### ISSUE THREAD

**Issue by suntimer24** [forrestguice/SuntimesWidget#843]
**Describe the bug**
See title of the issue.

**To Reproduce**
Open the main app. 
Open the moon dialog. 
See the date and time for any major phase in the second row. 
Tip on the actual moon pahse in the first row and go to that date and time of the moon phase you choosed in the second row.
Result: the date is identically, but time is differs.

**Expected behavior**
Same date and time in both rows.

**Screenshots**
![Bug_Moondialog_001](https://github.com/user-attachments/assets/16dc1174-d099-4769-8c50-0709e96580d0)
![Bug_Moondialog_002](https://github.com/user-attachments/assets/806c246e-cd42-4d78-9cea-71600737f051)

**Version Info:**
 - App Version: [0.16.3]
 - Android Version: [Android 11 (LineageOS 18.1)] (there are no longer new versions of LOS available for my device)

**Additional context**
Notice that it shows "Waning Gibbous" instead of "Full Moon".
That is some super strange behaviour caused like this: 
The power button on my device is broken, so I can not take screenshots. 
But I can record a video of my screen and then make a screenshot of a part of that video while playing it. 
As soon as I start the record, the app switching from displaying "Full Moon" to "Waning Gibbous".
 Don't ask me why! 
Anyway, nothing else is changing and the bug was noticed while I was not recording, so just ignore that is does not show "Full Moon". ;)

"Add any other information about the problem here.

**Comment by forrestguice** [comment]
I've been testing this by tapping a major phase, then `View Date -> Moon`, and then using the `>` and `<` controls.

The label in the first row is simply wrong, but the times given in the second row are the correct major phase dates.
After reviewing the code, it seems the first row is showing a "daily label" (as shown main card), which doesn't get updated when stepping `>` or `<`.

I think the expected behavior is that the label changes from one minor phase to the next at the time of each major phase. e.g. from waxing to waning gibbous. Since the major phases are instants, their labels wouldn't normally be shown.
